Repository TTT-2/TTT2, pull requests merged in 2019-07, with the labels that each got.

#354 Advanced Font System
  gamemodes/terrortown/gamemode/client/cl_fonts.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_hudswitcher.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/pure_skin_element.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttmstack/pure_skin_mstack.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttpunchometer/pure_skin_punchometer.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttroundinfo/pure_skin_roundinfo.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttsidebar/pure_skin_sidebar.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/ttttarget/pure_skin_target.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/pure_skin_wswitch.lua
  gamemodes/terrortown/gamemode/shared/huds/base_huds/scalable_hud/cl_init.lua
  gamemodes/terrortown/gamemode/shared/huds/pure_skin/cl_init.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
Labels: enhancement

#347 Pickup HUD Element
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_hudpickup.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/base_stacking_element.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttpickup/old_ttt_pickup.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttpickup/pure_skin_pickup.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/old_ttt_wswitch.lua
  gamemodes/terrortown/gamemode/shared/huds/old_ttt/cl_init.lua
  gamemodes/terrortown/gamemode/shared/huds/pure_skin/cl_init.lua
  lua/autorun/ttt2_force_download.lua
  materials/vgui/ttt/pickup/icon_ammo.png
  materials/vgui/ttt/pickup/icon_class.png
  materials/vgui/ttt/pickup/icon_extra.png
  materials/vgui/ttt/pickup/icon_heavy.png
  materials/vgui/ttt/pickup/icon_nades.png
  materials/vgui/ttt/pickup/icon_pistol.png
  materials/vgui/ttt/pickup/icon_special.png
Labels: enhancement

#359 [WIP] Doc
  config.ld
  docs/index.html
  docs/ldoc.css
  docs/modules/HUD.html
  docs/modules/HUDELEMENT.html
  docs/modules/bind.html
  docs/modules/hudelements.html
  docs/modules/huds.html
  docs/modules/items.html
  docs/modules/marks.html
  docs/modules/roles.html
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/hud_element_base/cl_init.lua
  gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua
  lua/includes/modules/hudelements.lua
  lua/includes/modules/huds.lua
  lua/includes/modules/items.lua
  lua/includes/modules/marks.lua
  lua/includes/modules/roles.lua
Labels: enhancement

#362 Add StaminaMult Hook to sh_sprint.lua
  gamemodes/terrortown/gamemode/shared/sh_sprint.lua
Labels: enhancement

#365 Use extra modifier table to support multiple hooking
  gamemodes/terrortown/gamemode/shared/sh_sprint.lua
Labels: enhancement, important

#367 Removed old docs files
  config.ld
  docs/index.html
  docs/ldoc.css
  docs/modules/DISGUISE.html
  docs/modules/HUD.html
  docs/modules/HUDELEMENT.html
  docs/modules/ITEM.html
  docs/modules/WEAPON.html
  docs/modules/WEPS.html
  docs/modules/bind.html
  docs/modules/favorites_db.html
  docs/modules/hudelements.html
  docs/modules/huds.html
  docs/modules/items.html
  docs/modules/marks.html
  docs/modules/roles.html
  docs/modules/terrortown.entities.items.item_ttt_armor.html
  docs/modules/terrortown.entities.items.item_ttt_disguiser.html
Labels: Documentation
