Repository TTT-2/TTT2, pull requests merged in 2020-06, with the labels that each got.

#556 Fix max roles
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
Labels: accepted, priority/critical

#559 Doors: Move destruction to next frame to avoid "area portals"
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_door.lua
Labels: accepted, enhancement

#558 Roleselection: Fixed innocent subrole selection
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  gamemodes/terrortown/gamemode/shared/sh_door.lua
Labels: accepted, bug, priority/critical

#565 Plymeta: Fixed revive fail function reference reset
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
Labels: accepted, bug

#566 Meta: Updated contributing guidelines
  CONTRIBUTING.md
Labels: accepted, skip/changelog

#568 AddonChecker: Reworked List and Cleanup
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
Labels: accepted, enhancement, needs testing, priority/low

#560 TargetID: Added hooks for modification
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_target_data.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: accepted, enhancement, needs testing

#573 DNA Scanner HUDElement Fix
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/hud_elements/tttdnascanner/pure_skin_dnascanner.lua
Labels: accepted, bug, priority/low

#572 Updated Italian with last string and one little fix
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
Labels: accepted, enhancement, priority/low

#564 Disguiser: Rework
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_lang.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/sh_weaponry.lua
  lua/terrortown/entities/items/item_ttt_disguiser.lua
Labels: accepted, priority/low, status/needs validation, type/enhancement

#584 ITEMS: Moved legacy item initialization to items module
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_item_module.lua
  lua/includes/modules/items.lua
Labels: priority/low, severity/minor, status/needs validation, type/enhancement

#577 Revival: Added IsValid check to fix problem with reason reset on connect
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
Labels: accepted, priority/low, type/enhancement

#583 HUD: Shadow texture fix for low quality settings (Pure Skin)
  CHANGELOG.md
  materials/vgui/ttt/dynamic/hud_components/shadow_border.vtf
Labels: accepted, priority/low, severity/cosmetic, type/bug

#582 Plymeta: Remove "Is{ROLENAME}" functions
  CHANGELOG.md
  lua/includes/modules/roles.lua
Labels: accepted, priority/low, type/enhancement

#571 Radar: added ForceScan
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_cvar_handler.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/terrortown/entities/items/item_base/shared.lua
  lua/terrortown/entities/items/item_ttt_radar/init.lua
Labels: accepted, priority/low, status/needs validation, type/enhancement

#585 ttt_round_end now gets reset when the map changes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_main.lua
Labels: accepted, priority/low, severity/cosmetic, status/needs validation, type/enhancement

#588 fixed image in confirmation notification for corpses from bots
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
Labels: accepted, priority/low, severity/cosmetic, status/needs validation, type/enhancement

#589 Roleselection: Do not reseed the RNG just before role selection
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
Labels: accepted, priority/high, severity/major, type/enhancement

#590 Deprecation: Fix not using GetOwner()
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
Labels: accepted, priority/low, skip/changelog, type/enhancement

#591 Cleanup: Move round state hooks & remove hook add
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
Labels: accepted, priority/medium, severity/moderate, skip/changelog, type/enhancement

#593 SWEP: HUD help rework
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttdnascanner/pure_skin_dnascanner.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  materials/vgui/ttt/hudhelp/lmb.vmt
  materials/vgui/ttt/hudhelp/lmb.vtf
  materials/vgui/ttt/hudhelp/rmb.vmt
  materials/vgui/ttt/hudhelp/rmb.vtf
Labels: accepted, priority/low, type/enhancement

#598 Score panel: Fix column translation
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_scoring.lua
Labels: accepted, priority/low, severity/cosmetic, type/enhancement

#599 HandModels: fixed hand models not updating correctly
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: accepted, priority/low, severity/cosmetic, type/bug

#597 Gameplay: Players who disconnect now leave a corpse
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: accepted, priority/low, type/enhancement

#600 Crosshair: Dot
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
Labels: accepted, priority/low, severity/cosmetic

#601 Release: Changelog & Versionbump
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted, status/needs validation, type/enhancement

#604 Remove Menof36go from VIP
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
Labels: skip/changelog

#603 RoleSync: Changed when roles are getting synced to clients
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_networking.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
Labels: accepted, priority/high, type/enhancement
