Repository TTT-2/TTT2, pull requests merged in 2020-08, with the labels that each got.

#625 Language: Add Chinese Simplified lang strings
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/simpchinese.lua
Labels: accepted, type/enhancement

#627 Spectators: Stop teleporting players to players they're not spectating
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: accepted, priority/low

#623 Language: Add Spanish translation
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/spanish.lua
Labels: accepted, type/enhancement

#624 Fileloader: Introduced a new file loader to TTT2
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_lang.lua
  lua/ttt2/libraries/fileloader.lua
Labels: accepted, type/feature

#629 Fetch: improvements in avatar fetching / some internal structure changes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_search.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  lua/autorun/client/b-draw_lib.lua
  lua/autorun/server/ttt2_force_download.lua
  materials/vgui/ttt/b-draw/icon_avatar_bot.vmt
  materials/vgui/ttt/b-draw/icon_avatar_bot.vtf
  materials/vgui/ttt/b-draw/icon_avatar_default.vmt
  materials/vgui/ttt/b-draw/icon_avatar_default.vtf
Labels: accepted, status/needs validation, type/enhancement

#630 TargetID: Render detective icon for all teams
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: accepted, type/enhancement

#628 Shop: Doubleclick buying, Coroutine loading and small fixes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_simpleicon.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/lang/simpchinese.lua
  gamemodes/terrortown/gamemode/shared/lang/spanish.lua
Labels: accepted, priority/low, type/enhancement

#631 VIP: Add new VIP users
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
Labels: skip/changelog

#633 Bumb gamemode version
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: skip/changelog

#636 Fetch: changed a '*' to a '-'
  CHANGELOG.md
  lua/autorun/client/b-draw_lib.lua
Labels: accepted, type/enhancement

#634 Shop: Added ConVar to toggle double-click buying
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/lang/simpchinese.lua
  gamemodes/terrortown/gamemode/shared/lang/spanish.lua
  lua/autorun/ttt_bem_autorun.lua
Labels: accepted, type/enhancement

#637 CI: Move glualint workflow to github action
  .github/workflows/ci.yml
Labels: accepted, skip/changelog, type/enhancement

#635 Language: Add a Japanese translation.
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/japanese.lua
Labels: accepted, type/enhancement

#638 HUD: Fix saving keys table to be unique for each HUD
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua
Labels: accepted, type/enhancement

#639 Fetch: fixes for drawing web images
  CHANGELOG.md
  lua/autorun/client/b-draw_lib.lua
Labels: accepted, type/enhancement

#602 WeaponPickup: Rework
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_weapon_pickup.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/lang/simpchinese.lua
  gamemodes/terrortown/gamemode/shared/lang/spanish.lua
Labels: accepted, priority/low, type/enhancement

#641 Language: Spanish translation update
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/spanish.lua
Labels: accepted, type/enhancement
