Repository TTT-2/TTT2, pull requests merged in 2020-07, with the labels that each got.

#608 Contributing: Added line regarding github conversations
  CONTRIBUTING.md
Labels: skip/changelog

#609 Issue template: Updated FAQ link, added existing issues link
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: skip/changelog

#613 HUDManager: Fix saving forcedHUD and defaultHUD values to DB
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_hud_manager.lua
Labels: accepted, priority/low, severity/moderate, type/enhancement

#612 Radar: Make bomb.team optional to fix compatibility
  CHANGELOG.md
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
Labels: accepted, priority/low, severity/minor, status/needs validation, type/enhancement

#614 Corpses: Fix multiple corpses
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: accepted, priority/low, severity/minor, type/enhancement

#616 Update sv_addonchecker.lua: Removed updated and now compatible Addons
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: accepted, skip/changelog

#620 EPOP docs: Fixed wrong default value in epop docstring
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_eventpopup.lua
Labels: documentation, priority/low

#607 Overhead Icons: Changed detective overhead icon to show to innocents
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: accepted, priority/low, type/bug
