Repository TTT-2/TTT2, pull requests merged in 2020-09, with the labels that each got.

#645 TargetID: Fix weapon key info
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: accepted, type/enhancement

#647 Scoreboard: Team indicator
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
Labels: accepted, priority/low, severity/minor, type/enhancement

#648 Util functions: Added table.ExtractRandomEntry(tbl, filterFn)
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_util.lua
  lua/ttt2/extensions/table.lua
Labels: accepted, priority/low, type/feature

#652 Call Detective Hook: added serverside hook on "call detective"
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
Labels: accepted, priority/low, type/feature

#654 DNA Scanner Crash: Added a check to prevent crash if using an old weapon base
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
Labels: accepted, priority/high, type/bug

#655 Speed: Fix initialization of oldval
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_speed.lua
Labels: accepted, priority/low, severity/minor
