Repository TTT-2/TTT2, pull requests merged in 2020-04, with the labels that each got.

#488 Streamlined Markdown Changelog
  CHANGELOG.md
Labels: accepted, documentation, priority/low

#508 Small ROLE improvements
  .gitignore
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/includes/modules/roles.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
Labels: accepted, enhancement, priority/low

#513 Armor headshot handling
  gamemodes/terrortown/gamemode/server/sv_armor.lua
Labels: accepted, enhancement, priority/low

#518 Move HUD Manager to the new networking system
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_network_sync.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_hudswitcher.lua
  gamemodes/terrortown/gamemode/server/sv_hud_manager.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_network_sync.lua
  gamemodes/terrortown/gamemode/shared/sh_hud_manager.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted, enhancement

#520 Targetid fixes
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  lua/autorun/server/ttt2_force_download.lua
  materials/vgui/ttt/tid/tid_big_door.vmt
  materials/vgui/ttt/tid/tid_big_door.vtf
Labels: accepted, enhancement

#516 Adding essential TTT2 items
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  lua/autorun/server/ttt2_force_download.lua
  lua/terrortown/entities/items/item_ttt_nodrowningdmg.lua
  lua/terrortown/entities/items/item_ttt_noenergydmg.lua
  lua/terrortown/entities/items/item_ttt_noexplosiondmg.lua
  lua/terrortown/entities/items/item_ttt_nofalldmg.lua
  lua/terrortown/entities/items/item_ttt_nofiredmg.lua
  lua/terrortown/entities/items/item_ttt_nohazarddmg.lua
  lua/terrortown/entities/items/item_ttt_nopropdmg.lua
  lua/terrortown/entities/items/item_ttt_speedrun.lua
  materials/vgui/ttt/icon_armor.vtf
  materials/vgui/ttt/icon_nodrowningdmg.vmt
  materials/vgui/ttt/icon_nodrowningdmg.vtf
  materials/vgui/ttt/icon_noenergydmg.vmt
  materials/vgui/ttt/icon_noenergydmg.vtf
  materials/vgui/ttt/icon_noexplosiondmg.vmt
  materials/vgui/ttt/icon_noexplosiondmg.vtf
  materials/vgui/ttt/icon_nofalldmg.vmt
  materials/vgui/ttt/icon_nofalldmg.vtf
  materials/vgui/ttt/icon_nofiredmg.vmt
  materials/vgui/ttt/icon_nofiredmg.vtf
  materials/vgui/ttt/icon_nohazarddmg.vmt
  materials/vgui/ttt/icon_nohazarddmg.vtf
  materials/vgui/ttt/icon_nopropdmg.vmt
  materials/vgui/ttt/icon_nopropdmg.vtf
  materials/vgui/ttt/icon_speedrun.vmt
  materials/vgui/ttt/icon_speedrun.vtf
  materials/vgui/ttt/perks/hud_nodrowningdmg.png
  materials/vgui/ttt/perks/hud_noenergydmg.png
  materials/vgui/ttt/perks/hud_noexplosiondmg.png
  materials/vgui/ttt/perks/hud_nofalldmg.png
  materials/vgui/ttt/perks/hud_nofiredmg.png
  materials/vgui/ttt/perks/hud_nohazarddmg.png
  materials/vgui/ttt/perks/hud_nopropdmg.png
  materials/vgui/ttt/perks/hud_speedrun.png
Labels: accepted, enhancement

#502 Added missing translations after Tim's cleanup
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
Labels: accepted, enhancement, waiting

#503 Added some missing strings
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
Labels: accepted, enhancement, waiting

#514 Added `TTT2ClientRadioCommand` hook to prevent clientside radio cmds
  gamemodes/terrortown/gamemode/client/cl_radio.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
Labels: accepted, enhancement, priority/low

#515 Added GAMEMODE.roundCount and cleaned GAMEMODE var usage
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
Labels: accepted, enhancement, priority/low
