Repository TTT-2/TTT2, pull requests merged in 2020-10, with the labels that each got.

#665 Update S. Chinese localization w/ new phrases
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/simpchinese.lua
Labels: accepted, priority/low, type/enhancement

#491 TargetID: Scalability
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_fonts.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/extensions/draw.lua
  lua/ttt2/extensions/surface.lua
  lua/ttt2/libraries/drawsc.lua
  lua/ttt2/libraries/fonts.lua
Labels: accepted, priority/low, type/enhancement

#671 Language: Update italian
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
Labels: accepted, skip/changelog, type/enhancement

#649 Roleselection: Layering
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_logic_role.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_rolelayering.lua
  gamemodes/terrortown/gamemode/shared/sh_sql.lua
Labels: accepted, type/feature

#672 Weapon Pickup: Fixed pickup bug
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
Labels: accepted, type/bug

#675 Overhead Icon: Fixed material name
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: skip/changelog

#681 C4: Removed defuse restriction for teammates
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/japanese.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/lang/simpchinese.lua
  gamemodes/terrortown/gamemode/shared/lang/spanish.lua
Labels: accepted, priority/low, type/bug

#594 ORM: Added object relational model to simplify DML/DSL queries
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/extensions/sql.lua
  lua/ttt2/libraries/orm.lua
Labels: accepted, priority/low, type/feature

#682 removed inclusion of non-existant file
  gamemodes/terrortown/gamemode/shared/sh_include.lua
Labels: accepted, skip/changelog

#667 Event System
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_scoring.lua
  gamemodes/terrortown/gamemode/client/cl_scoring_events.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_scoring.lua
  gamemodes/terrortown/gamemode/shared/events/base_event.lua
  gamemodes/terrortown/gamemode/shared/events/bodyfound.lua
  gamemodes/terrortown/gamemode/shared/events/c4disarm.lua
  gamemodes/terrortown/gamemode/shared/events/c4explode.lua
  gamemodes/terrortown/gamemode/shared/events/c4plant.lua
  gamemodes/terrortown/gamemode/shared/events/creditfound.lua
  gamemodes/terrortown/gamemode/shared/events/finish.lua
  gamemodes/terrortown/gamemode/shared/events/game.lua
  gamemodes/terrortown/gamemode/shared/events/kill.lua
  gamemodes/terrortown/gamemode/shared/events/respawn.lua
  gamemodes/terrortown/gamemode/shared/events/rolechange.lua
  gamemodes/terrortown/gamemode/shared/events/selected.lua
  gamemodes/terrortown/gamemode/shared/events/spawn.lua
  gamemodes/terrortown/gamemode/shared/events/teamchange.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_scoring.lua
  lua/terrortown/entities/roles/detective/shared.lua
  lua/terrortown/entities/roles/innocent/shared.lua
  lua/terrortown/entities/roles/traitor/shared.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
  lua/ttt2/libraries/events.lua
  lua/ttt2/libraries/fileloader.lua
Labels: accepted, priority/low, type/enhancement

#689 Update japanese.lua
  gamemodes/terrortown/gamemode/shared/lang/japanese.lua
Labels: skip/changelog
