Repository TTT-2/TTT2, pull requests merged in 2020-12, with the labels that each got.

#699 Update README.md
  README.md
Labels: accepted, priority/low, skip/changelog

#669 TargetID: Refactoring of HUDDrawTargetID
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_target_data.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/libraries/targetid.lua
Labels: accepted, type/feature

#692 Classbuilder: Added a new classbuilder module
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/extensions/math.lua
  lua/ttt2/extensions/string.lua
  lua/ttt2/extensions/table.lua
  lua/ttt2/extensions/util.lua
  lua/ttt2/libraries/classbuilder.lua
  lua/ttt2/libraries/events.lua
  lua/ttt2/libraries/none.lua
Labels: accepted, priority/low

#701 TargetID-Fix: Initializing convars later
  CHANGELOG.md
  lua/ttt2/libraries/targetid.lua
Labels: accepted

#702 Addonchecker: Removed some updated addons
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: accepted

#703 [FIX, util] Fixed library cache name
  lua/ttt2/extensions/util.lua
Labels: skip/changelog

#694 Lang: Cleanup and Menu Additions
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_help/populate_language.lua
  gamemodes/terrortown/gamemode/client/cl_lang.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dlabel_ttt2.lua
  gamemodes/terrortown/gamemode/shared/lang/chef.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
  lua/ttt2/extensions/draw.lua
  lua/ttt2/extensions/table.lua
Labels: accepted, type/enhancement
