Repository TTT-2/TTT2, pull requests merged in 2020-01, with the labels that each got.

#414 ConVar for compatibility with Enhanced Playermodel Selector
  .gitignore
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: enhancement

#410 Improved damage indicator
  gamemodes/terrortown/gamemode/client/cl_damage_indicator.lua
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/autorun/ttt2_force_download.lua
  materials/vgui/ttt/dmgindicator/themes/Default.png
  materials/vgui/ttt/dmgindicator/themes/Simple.png
  materials/vgui/ttt/dmgindicator/themes/Vanilla.png
Labels: enhancement

#424 Fix weapon switch and minor german localization changes
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_weapon_pickup.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
Labels: accepted, priority/important

#442 Stamina autoregen on exhaustion
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_sprint.lua
Labels: enhancement

#441 Rework shop funcs
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/server/sv_shopeditor.lua
  gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_item_module.lua
Labels: enhancement

#448 Move voice binds to TTT2 and various
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/client/cl_weapon_pickup.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_voice.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  lua/bind/cl_init.lua
Labels: accepted, needs testing

#452 Hotfix Limited
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: enhancement, priority/important
