Repository TTT-2/TTT2, pull requests merged in 2020-05, with the labels that each got.

#522 Team sorting error fix
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_team.lua
Labels: accepted, priority/low

#523 improved epop
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_eventpopup.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/ttteventpopup/pure_skin_eventpopup.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
Labels: accepted, enhancement, priority/low

#535 TTT2NET: Fix naming
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_network_sync.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_hudswitcher.lua
  gamemodes/terrortown/gamemode/server/sv_hud_manager.lua
  gamemodes/terrortown/gamemode/server/sv_network_sync.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
  gamemodes/terrortown/gamemode/shared/sh_network_sync.lua
Labels: accepted

#530 Radar Rework
  CHANGELOG.md
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
  lua/terrortown/entities/items/item_ttt_radar/init.lua
  lua/terrortown/entities/items/item_ttt_radar/shared.lua
Labels: accepted, enhancement, priority/low

#525 introduced speed system
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_speed.lua
  lua/terrortown/entities/items/item_ttt_speedrun.lua
Labels: accepted, enhancement, priority/low

#533 introduced outputRegistry and updated door states
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/sh_door.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  lua/autorun/server/ttt2_force_download.lua
  lua/ttt2/libraries/door.lua
  lua/ttt2/libraries/entity_outputs.lua
  materials/vgui/ttt/tid/tid_destructible.vmt
  materials/vgui/ttt/tid/tid_destructible.vtf
Labels: accepted, enhancement, priority/low

#531 Thermal vision module
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/extensions/table.lua
  lua/ttt2/libraries/thermalvision.lua
Labels: accepted, enhancement, priority/low

#517 Role selection rework
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/terrortown/entities/roles/innocent/shared.lua
  lua/terrortown/entities/roles/ttt_role_base/init.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
Labels: accepted, enhancement, needs testing

#528 Revival Rework
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_chat.lua
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_eventpopup.lua
  gamemodes/terrortown/gamemode/client/cl_fonts.lua
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_hudpickup.lua
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/client/cl_scoreboard.lua
  gamemodes/terrortown/gamemode/client/cl_target_data.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_ent_replace.lua
  gamemodes/terrortown/gamemode/server/sv_entity.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_propspec.lua
  gamemodes/terrortown/gamemode/server/sv_voice.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttrevivalinfo/old_ttt_revival.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttrevivalinfo/pure_skin_revival.lua
  gamemodes/terrortown/gamemode/shared/huds/old_ttt/cl_init.lua
  gamemodes/terrortown/gamemode/shared/huds/pure_skin/cl_init.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
  gamemodes/terrortown/gamemode/shared/sh_corpse.lua
  gamemodes/terrortown/gamemode/shared/sh_decal.lua
  gamemodes/terrortown/gamemode/shared/sh_door.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_util.lua
  lua/autorun/client/draw_ext.lua
  lua/autorun/server/ttt2_force_download.lua
  lua/terrortown/entities/items/item_ttt_radar/init.lua
  lua/ttt2/extensions/table.lua
  lua/ttt2/libraries/door.lua
  lua/ttt2/libraries/entity_outputs.lua
  lua/ttt2/libraries/spawn.lua
  materials/vgui/ttt/hud_blocking_revival.vmt
  materials/vgui/ttt/hud_blocking_revival.vtf
Labels: accepted, enhancement, priority/low

#524 Printmessage overwrite and EPOP Proxy
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_eventpopup.lua
  gamemodes/terrortown/gamemode/client/cl_lang.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_eventpopup.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_lang.lua
  gamemodes/terrortown/gamemode/shared/sh_printmessage_override.lua
Labels: accepted, enhancement, needs testing, priority/low

#538 New strings and fixes
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
Labels: accepted, enhancement, priority/low

#544 fixed radar on client
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
Labels: accepted, bug, needs testing

#543 fixed door grouping
  lua/ttt2/libraries/door.lua
Labels: accepted, bug, needs testing

#541 Adjust CLSCORE to fix clipping title
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_scoring.lua
Labels: accepted, enhancement, priority/low

#548 Corpse dete only
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/lang/italian.lua
  gamemodes/terrortown/gamemode/shared/lang/polish.lua
  gamemodes/terrortown/gamemode/shared/lang/russian.lua
Labels: accepted, enhancement, priority/low

#549 Adjust CLSCORE to use the new stream net functions
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_scoring.lua
  gamemodes/terrortown/gamemode/server/sv_scoring.lua
Labels: accepted, priority/low
