Repository TTT-2/TTT2, pull requests merged in 2020-11, with the labels that each got.

#691 French update
  gamemodes/terrortown/gamemode/shared/lang/french.lua
Labels: skip/changelog

#693 CI: Add NeoDoc lint step
  .github/workflows/ci.yml
Labels: accepted, documentation, skip/changelog, type/enhancement

#685 Roleselection: Fixed forced roles not being subtracted from the roles amount
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
Labels: accepted, priority/low, type/bug
