Repository TTT-2/TTT2, pull requests merged in 2020-02, with the labels that each got.

#455 added preventSprint to doubletap feature
  gamemodes/terrortown/gamemode/shared/sh_sprint.lua
Labels: enhancement, priority/low

#454 reworked audio hooks
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_voice.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_voice.lua
Labels: enhancement, priority/low

#457 Fix replicated convars
  gamemodes/terrortown/entities/entities/ttt_traitor_button/shared.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  lua/autorun/ttt_bem_autorun.lua
  lua/includes/modules/roles.lua
Labels: accepted

#453 Issue template update
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: priority/low

#456 Allow hold aim instead of toggle
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
Labels: enhancement

#458 reworked targetID
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  gamemodes/terrortown/gamemode/client/cl_lang.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_target_data.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/autorun/ttt2_force_download.lua
  materials/vgui/ttt/tid_credits.vmt
  materials/vgui/ttt/tid_credits.vtf
  materials/vgui/ttt/tid_detective.vmt
  materials/vgui/ttt/tid_detective.vtf
Labels: enhancement, priority/low

#461 Additional target id stuff
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_target_data.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua
  gamemodes/terrortown/gamemode/shared/lang/english.lua
  gamemodes/terrortown/gamemode/shared/lang/german.lua
  gamemodes/terrortown/gamemode/shared/sh_armor.lua
  gamemodes/terrortown/gamemode/shared/sh_door.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/autorun/ttt2_force_download.lua
  materials/vgui/ttt/tid_locked.vmt
  materials/vgui/ttt/tid_locked.vtf
Labels: accepted, enhancement, priority/low

#466 added addon language file support
  gamemodes/terrortown/gamemode/client/cl_lang.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_lang.lua
Labels: accepted, enhancement

#467 Networked data tables
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_network_sync.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_network_sync.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_network_sync.lua
  lua/includes/modules/pon.lua
  lua/ttt2/extensions/net.lua
  lua/ttt2/extensions/string.lua
  lua/ttt2/extensions/table.lua
Labels: accepted, enhancement, needs testing, priority/important

#471 Remove sideeffects from path param | Add NWVar syncing
  gamemodes/terrortown/gamemode/client/cl_network_sync.lua
  gamemodes/terrortown/gamemode/server/sv_network_sync.lua
Labels: accepted, enhancement, priority/critical

#470 TTT2NET: Transition body confirm to new synced data tables
  gamemodes/terrortown/gamemode/client/cl_search.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_networking.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/autorun/gs_crazyphysics.lua
Labels: accepted, needs testing, priority/important
