Repository TTT-2/TTT2, pull requests merged in 2021-06, with the labels that each got.

#819 Loading screen: Remove custom loading screen
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_loadingscreen.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/autorun/server/ttt2_force_download.lua
  materials/vgui/ttt/loadingscreen/img/bg.jpg
  materials/vgui/ttt/loadingscreen/img/ttt2_loading_logo.png
  materials/vgui/ttt/loadingscreen/loading.vtf
Labels: accepted

#815 F1 menu: rolelayering integration
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/ddragbase_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/droleimage_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/drolelayeringreceiver_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/drolelayeringsender_ttt2.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_rolelayering.lua
  lua/terrortown/menus/gamemode/administration/rolelayering.lua
Labels: accepted, priority/low, type/enhancement

#817 Shopeditor: Move Custom and linked shops to F1 Menu
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcard_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_shopeditor.lua
  lua/terrortown/menus/gamemode/shops.lua
  lua/terrortown/menus/gamemode/shops/base_shops.lua
  materials/vgui/ttt/vskin/card_added.vmt
  materials/vgui/ttt/vskin/card_added.vtf
  materials/vgui/ttt/vskin/card_removed.vmt
  materials/vgui/ttt/vskin/card_removed.vtf
Labels: priority/low, severity/minor, type/enhancement

#822 Credit transfer: Sort teammates first and show indicator
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_transfer.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
Labels: accepted, type/enhancement

#821 Cleanup library structure
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/shared/sh_hud_module.lua
  gamemodes/terrortown/gamemode/shared/sh_hudelement_module.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_item_module.lua
  lua/autorun/ttt_bem_autorun.lua
  lua/autorun/ttt_bind_autorun.lua
  lua/favorites_db.lua
  lua/ttt2/libraries/bind.lua
  lua/ttt2/libraries/hudelements.lua
  lua/ttt2/libraries/huds.lua
  lua/ttt2/libraries/items.lua
  lua/ttt2/libraries/pon.lua
Labels: accepted, type/enhancement

#823 Cleanup: Folder structure
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_lang.lua
  lua/terrortown/events/base_event.lua
  lua/terrortown/events/bodyfound.lua
  lua/terrortown/events/c4disarm.lua
  lua/terrortown/events/c4explode.lua
  lua/terrortown/events/c4plant.lua
  lua/terrortown/events/creditfound.lua
  lua/terrortown/events/finish.lua
  lua/terrortown/events/game.lua
  lua/terrortown/events/kill.lua
  lua/terrortown/events/respawn.lua
  lua/terrortown/events/rolechange.lua
  lua/terrortown/events/selected.lua
  lua/terrortown/events/spawn.lua
  lua/terrortown/lang/chef.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/vskin/dark.lua
  lua/terrortown/vskin/light.lua
  lua/ttt2/libraries/events.lua
Labels: accepted, type/enhancement

#824 Fix: Items library function references
  lua/ttt2/libraries/items.lua
Labels: accepted, skip/changelog, type/enhancement

#809 Map Integration: Map role check
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_logic_role.lua
  gamemodes/terrortown/entities/entities/ttt_traitor_check.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
  lua/ttt2/extensions/util.lua
  lua/ttt2/libraries/roles.lua
Labels: accepted, type/enhancement

#826 [Release] Add changelog and bump version number to 0.9.0b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted, skip/changelog

#828 Fix: Shop convars being initialized as shared again
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/shared/sh_cvar_handler.lua
Labels: accepted, priority/critical, severity/major, type/enhancement

#829 [Release] Add changelog and bump version to 0.9.1b for hotfix release
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted

#830 Classbuilder: added recursion
  CHANGELOG.md
  lua/ttt2/extensions/table.lua
  lua/ttt2/libraries/classbuilder.lua
Labels: priority/critical, type/bug

#834 Lang: Updated Japanese Translation
  CHANGELOG.md
  lua/terrortown/lang/ja.lua
Labels: accepted, priority/low, severity/cosmetic

#836 pure_skin: consistent text positioning in pure_skin bar
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/pure_skin_element.lua
Labels: accepted, priority/low, severity/cosmetic

#835 F1 Menu: Added general Searchbar and Fullsize icons for submenus
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_help.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsearchbar_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenubutton_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenulist_ttt2.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/menus/gamemode/addons.lua
  lua/terrortown/menus/gamemode/base_gamemodemenu.lua
  lua/terrortown/menus/gamemode/changelog.lua
  lua/terrortown/menus/gamemode/equipment.lua
  lua/terrortown/menus/gamemode/shops.lua
Labels: accepted, priority/low, severity/cosmetic
