Repository TTT-2/TTT2, pull requests merged in 2021-11, with the labels that each got.

#910 Role Enhancement: Called Policing Role Hook and Added Docs
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_chat.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
  gamemodes/terrortown/gamemode/server/sv_networking.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
Labels: type/bug, type/enhancement, priority/low, accepted

#908 Revival: Add Block Modes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/enhancement, priority/low, accepted

#911 Weapon Spawn: Fix late random weapon spawns on maps like kakariko
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_random_ammo.lua
  gamemodes/terrortown/entities/entities/ttt_random_weapon.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  lua/ttt2/libraries/entspawn.lua
Labels: type/bug, accepted, priority/medium, severity/major

#913 Roleselection: Fix available baseroles calculation by considering maxPlys when filtering
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
Labels: type/bug, priority/high, accepted, severity/major

#918 Playermodels: Fixed Random Selection on Map Change
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_main.lua
Labels: type/bug, priority/low, accepted

#909 F1 Menu: Moved Further ConVars
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_confgrenade_proj.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_confgrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
  gamemodes/terrortown/gamemode/client/cl_armor.lua
  gamemodes/terrortown/gamemode/client/cl_lang.lua
  gamemodes/terrortown/gamemode/client/cl_scoring.lua
  gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/server/sv_admin.lua
  gamemodes/terrortown/gamemode/server/sv_armor.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
  gamemodes/terrortown/gamemode/server/sv_karma.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/old_ttt_info.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua
  lua/autorun/server/ttt2_force_download.lua
  lua/terrortown/entities/items/item_base/shared.lua
  lua/terrortown/entities/items/item_ttt_armor.lua
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/administration/administration.lua
  lua/terrortown/menus/gamemode/administration/chat.lua
  lua/terrortown/menus/gamemode/administration/entspawn.lua
  lua/terrortown/menus/gamemode/administration/hud.lua
  lua/terrortown/menus/gamemode/administration/inventory.lua
  lua/terrortown/menus/gamemode/administration/karma.lua
  lua/terrortown/menus/gamemode/administration/mapentities.lua
  lua/terrortown/menus/gamemode/administration/playermodels.lua
  lua/terrortown/menus/gamemode/administration/playersettings.lua
  lua/terrortown/menus/gamemode/administration/randomshop.lua
  lua/terrortown/menus/gamemode/administration/rolelayering.lua
  lua/terrortown/menus/gamemode/administration/roles.lua
  lua/terrortown/menus/gamemode/administration/roundsetup.lua
  lua/terrortown/menus/gamemode/administration/sprint.lua
  lua/terrortown/menus/gamemode/equipment.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
  materials/vgui/ttt/icon_magneto_stick.vmt
  materials/vgui/ttt/icon_magneto_stick.vtf
Labels: type/enhancement, priority/low, accepted

#920 Weapon Pickup: Fixed Flying Weapons
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
Labels: type/bug, priority/low, accepted

#921 Overheadicons: Color icon based on role color
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: type/enhancement, accepted

#922 Role Agnostics: IsOmniscientRole
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/old_ttt_info.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttroundinfo/pure_skin_roundinfo.lua
  lua/terrortown/entities/roles/traitor/shared.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
Labels: type/enhancement, priority/low, accepted

#917 Revival: Renamed Revival Flag
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted, skip/changelog

#923 Weapon Pickup: Fixed Pickup if Autopickup is Disabled
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_weapon_pickup.lua
Labels: type/bug, priority/high, accepted, skip/changelog

#924 Overhead Icon: Made modifyable
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: type/enhancement, priority/low, accepted

#925 Release-0.11.0
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: documentation, accepted, skip/changelog

#927 Fix: Removed Unused Code
  gamemodes/terrortown/gamemode/client/cl_lang.lua
Labels: type/bug, accepted, skip/changelog, severity/minor

#926 fixed typo
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
Labels: accepted, skip/changelog

#930 Spawneditor: Fixed giving spawneditor when weapons are cached
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
Labels: type/bug, priority/low, accepted, severity/moderate

#932 Karma: Added Multiplicators
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_karma.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
Labels: type/enhancement, priority/low, accepted

#933 Damage Overlay: Fix unscaled damage being shown
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: type/bug, priority/low, accepted, severity/cosmetic

#934 Roles: Initial Traitor Button
  CHANGELOG.md
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
Labels: type/bug, priority/high, accepted

#928 Release 0.11.1
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: documentation, accepted

#935 Karma: Fix correct roleData karma multiplier
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_karma.lua
Labels: type/bug, priority/critical, accepted, severity/moderate

#936 Release v0.11.2b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: documentation, accepted

#938 ConVars: Fix theoretical indexing error at 0
  CHANGELOG.md
  lua/ttt2/extensions/cvars.lua
Labels: type/bug, priority/low, accepted, severity/minor

#939 Equipment Editor: Fix showing cached variables instead of synced ones
  CHANGELOG.md
  lua/terrortown/menus/gamemode/equipment.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/bug, priority/low, accepted, severity/cosmetic

#940 Release v0.11.3b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: documentation, accepted

#942 Docs: Fixes
  lua/ttt2/extensions/draw.lua
  lua/ttt2/libraries/credits.lua
Labels: type/enhancement, priority/low, accepted, skip/changelog

#947 update japanese translate
  CHANGELOG.md
  lua/terrortown/lang/ja.lua
Labels: type/enhancement, accepted
