Repository TTT-2/TTT2, pull requests merged in 2021-02, with the labels that each got.

#710 Language: English localization changes and improvements
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/en.lua
Labels: accepted, type/enhancement

#708 Language: Russian language update
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
Labels: accepted, type/enhancement, waiting

#722 Classbuilder: Fixed inheriting from same base
  CHANGELOG.md
  lua/ttt2/libraries/classbuilder.lua
  lua/ttt2/libraries/events.lua
Labels: accepted, priority/high, severity/major, type/bug

#728 Language: Updated Japanese localization
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
Labels: accepted, severity/cosmetic, type/enhancement

#730 Updated Japanese Translation
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
Labels: skip/changelog

#731 Compat: Add global alias for util.IsOffScreen
  CHANGELOG.md
  lua/ttt2/extensions/util.lua
Labels: accepted, type/enhancement

#732 Refactoring: Moving Rendering Modules to libraries
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/includes/modules/marks.lua
  lua/ttt2/libraries/marks.lua
  lua/ttt2/libraries/outline.lua
  lua/ttt2/libraries/thermalvision.lua
Labels: accepted, type/enhancement

#733 Update ja.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
Labels: accepted, severity/cosmetic, skip/changelog, type/enhancement
