Repository TTT-2/TTT2, pull requests merged in 2021-03, with the labels that each got.

#735 Fixes: Added TTT fixes (gmod branch)
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
Labels: accepted, priority/low, type/bug

#737 Fixed outline library
  CHANGELOG.md
  lua/ttt2/libraries/outline.lua
Labels: accepted, type/bug

#741 CI: fix CI by bumping glualint to v1.17.2
  .github/workflows/ci.yml
Labels: accepted, skip/changelog

#739 Language: Fixed Japanese Translation
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
Labels: accepted, severity/cosmetic, skip/changelog, type/enhancement

#742 [Release] Added changelog, bumped version and small GM-info fixes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted

#743 Meta: Document release process
  CHANGELOG.md
  RELEASE_PROCESS.md
Labels: accepted, skip/changelog
