Repository TTT-2/TTT2, pull requests merged in 2021-01, with the labels that each got.

#704 Lang: Fix variable name in SetActiveLanguage method
  gamemodes/terrortown/gamemode/client/cl_lang.lua
Labels: accepted, priority/critical, skip/changelog

#706 LANG: Fix indefinitely rebuilding language settings menu
  gamemodes/terrortown/gamemode/client/cl_help/populate_language.lua
  gamemodes/terrortown/gamemode/client/cl_lang.lua
  gamemodes/terrortown/gamemode/client/cl_radio.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
  gamemodes/terrortown/gamemode/shared/lang/chef.lua
  gamemodes/terrortown/gamemode/shared/sh_lang.lua
Labels: accepted, skip/changelog, type/bug

#707 CI: NeoDoc bump to v0.1.4
  .github/workflows/ci.yml
Labels: accepted, skip/changelog, type/enhancement

#677 Small rework of how credits are transfered (now includes a hook).
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_transfer.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
Labels: accepted, type/enhancement, waiting

#709 Language: French translation updates
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
Labels: accepted, skip/changelog, type/enhancement

#712 Player: Remove pointless notification
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: accepted, severity/cosmetic, type/enhancement

#711 Roleselection: Fix Layering
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
Labels: accepted, priority/low, severity/moderate, type/enhancement

#714 Badge: Added @Histalek as Dev and ZenBre4ker as VIP
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
Labels: accepted, skip/changelog

#715 Update glualint to 1.17.0
  .github/workflows/ci.yml
Labels: accepted, skip/changelog

#716 Language: German minor spelling and grammar fixes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/de.lua
Labels: accepted, type/enhancement

#717 Weapon - Magnetostick: Fix inno ragdoll pinning
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
Labels: accepted, priority/low, type/bug
