Repository TTT-2/TTT2, pull requests merged in 2021-04, with the labels that each got.

#744 Util: Fixed IsOffScreen function being global for compatibility
  CHANGELOG.md
  lua/ttt2/extensions/util.lua
Labels: accepted, type/enhancement

#797 Language: Updated German translation
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/de.lua
Labels: accepted, priority/low, severity/minor

#799 WIN_NONE: Fixed draw
  gamemodes/terrortown/gamemode/server/sv_main.lua
Labels: accepted, priority/high, skip/changelog, type/bug
