Repository TTT-2/TTT2, pull requests merged in 2021-07, with the labels that each got.

#839 Add Traditional Chinese, Fix Simplified Chinese
  CHANGELOG.md
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: accepted, priority/low, severity/cosmetic

#841 Hot-Reloading: Fixed data persistency on hotreload
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_network_sync.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_network_sync.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_network_sync.lua
  lua/ttt2/libraries/bind.lua
Labels: accepted, priority/high, severity/minor

#842 Shopeditor: Added Weapon spawn options
  gamemodes/terrortown/gamemode/shared/sh_shopeditor.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/menus/gamemode/equipment.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
  lua/ttt2/libraries/entspawnscript.lua
Labels: skip/changelog

#845 Revive: Prevent spectators about to revive from gathering player info
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: accepted, type/enhancement
