Repository TTT-2/TTT2, pull requests merged in 2021-08, with the labels that each got.

#840 Update ja.lua
  CHANGELOG.md
  lua/terrortown/lang/ja.lua
Labels: type/enhancement, priority/low, accepted, waiting

#850 Hotreload: Weapon hotreloading fix and persistent data across reloads
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
Labels: type/bug, priority/low, accepted, severity/minor

#852 Convars: Change server convars clientside as admin
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/terrortown/menus/gamemode/administration/randomshop.lua
  lua/terrortown/menus/gamemode/base_gamemodemenu.lua
  lua/ttt2/extensions/cvars.lua
Labels: type/enhancement, accepted, priority/medium

#853 Weapon spawn rework breaker
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  materials/vgui/ttt/tid/tid_big_ammo_deagle.vmt
  materials/vgui/ttt/tid/tid_big_ammo_mac10.vmt
  materials/vgui/ttt/tid/tid_big_ammo_pistol.vmt
  materials/vgui/ttt/tid/tid_big_ammo_random.vmt
  materials/vgui/ttt/tid/tid_big_ammo_rifle.vmt
  materials/vgui/ttt/tid/tid_big_ammo_shotgun.vmt
  materials/vgui/ttt/tid/tid_big_player.vmt
  materials/vgui/ttt/tid/tid_big_weapon_assault.vmt
  materials/vgui/ttt/tid/tid_big_weapon_melee.vmt
  materials/vgui/ttt/tid/tid_big_weapon_nade.vmt
  materials/vgui/ttt/tid/tid_big_weapon_pistol.vmt
  materials/vgui/ttt/tid/tid_big_weapon_random.vmt
  materials/vgui/ttt/tid/tid_big_weapon_shotgun.vmt
  materials/vgui/ttt/tid/tid_big_weapon_sniper.vmt
  materials/vgui/ttt/tid/tid_big_weapon_special.vmt
Labels: type/bug, accepted, skip/changelog, severity/cosmetic
