Repository TTT-2/TTT2, pull requests merged in 2021-05, with the labels that each got.

#800 Roundendscreen: Summarize events
  CHANGELOG.md
  lua/terrortown/menus/score/info.lua
Labels: accepted, priority/low

#803 Karma: Store changes and show on roundenscreen
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_scoring.lua
  gamemodes/terrortown/gamemode/server/sv_karma.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/events/base_event.lua
  gamemodes/terrortown/gamemode/shared/events/finish.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
  lua/terrortown/menus/score/info.lua
  lua/ttt2/libraries/eventdata.lua
  lua/ttt2/libraries/events.lua
Labels: accepted, priority/low

#806 Fixed c4 plant event references for GetText()
  gamemodes/terrortown/gamemode/shared/events/c4explode.lua
  gamemodes/terrortown/gamemode/shared/events/c4plant.lua
Labels: accepted, severity/minor, skip/changelog, type/enhancement

#807 Translation - French: Improvement
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
Labels: accepted, priority/low

#811 Footsteps: Fixed silenced footsteps when moving fast while crouching
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_main.lua
Labels: accepted, type/enhancement

#812 TeamChat: Fixed issue where base innocents could bypass chat hooks
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_chat.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
Labels: accepted, type/bug

#804 Shopeditor: Settings Rework
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_help/populate_administration.lua
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
  gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
  gamemodes/terrortown/gamemode/shared/sh_shopeditor.lua
Labels: accepted, priority/low, severity/minor

#813 Round End Screen: Fixing killer role/team for "something"
  gamemodes/terrortown/gamemode/shared/events/kill.lua
  gamemodes/terrortown/gamemode/shared/lang/de.lua
  gamemodes/terrortown/gamemode/shared/lang/en.lua
  gamemodes/terrortown/gamemode/shared/lang/es.lua
  gamemodes/terrortown/gamemode/shared/lang/fr.lua
  gamemodes/terrortown/gamemode/shared/lang/it.lua
  gamemodes/terrortown/gamemode/shared/lang/ja.lua
  gamemodes/terrortown/gamemode/shared/lang/pl.lua
  gamemodes/terrortown/gamemode/shared/lang/ru.lua
  gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua
Labels: accepted, priority/low, skip/changelog, type/bug
