Repository TTT-2/TTT2, pull requests merged in 2022-08, with the labels that each got.

#985 cd: Remove 'concurrency' stanza from deploy job
  .github/workflows/cd.yml
Labels: accepted, skip/changelog

#894 SQL Client Access: Shared database handling between client and server
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/terrortown/menus/gamemode/administration/playermodels.lua
  lua/ttt2/libraries/database.lua
  lua/ttt2/libraries/playermodels.lua
Labels: type/enhancement, priority/low, accepted, severity/minor

#986 Roles: Improve hotreloadability of Gamemode
  CHANGELOG.md
  lua/ttt2/libraries/roles.lua
Labels: type/enhancement, priority/low, severity/minor

#983 [Release] v0.11.5b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: priority/low, documentation, accepted, waiting
