Repository TTT-2/TTT2, pull requests merged in 2022-09, with the labels that each got.

#989 Language: Fixed and updated Chinese translation
  CHANGELOG.md
  lua/terrortown/lang/zh_hans.lua
Labels: type/enhancement, priority/low, accepted

#990 Fixed: Spawn editor TargetID not showing
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_spawninfo_ent.lua
Labels: type/bug, priority/low, accepted

#987 Roleselection: Fix not every role could be chosen
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
Labels: type/bug, accepted, priority/medium, severity/moderate

#997 Language: Fix some language identifiers for portuguese
  CHANGELOG.md
  lua/terrortown/lang/pt_br.lua
Labels: accepted, severity/cosmetic

#998 cd: Fix `deploy-to-dev` workflow not running on PRs from forks
  .github/workflows/cd.yml
Labels: accepted, skip/changelog

#999 guide: Add placeholder text to empty panels
  CHANGELOG.md
  lua/terrortown/menus/gamemode/guide/equipment.lua
  lua/terrortown/menus/gamemode/guide/gameplay.lua
  lua/terrortown/menus/gamemode/guide/roles.lua
Labels: type/enhancement, accepted, severity/cosmetic

#1000 cd: Fix double deploys for PRs from project branches
  .github/workflows/cd.yml
Labels: accepted, skip/changelog

#1001 [Release] v0.11.6b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted
