Repository TTT-2/TTT2, pull requests merged in 2022-07, with the labels that each got.

#975 Corrected incorrect translation
  CHANGELOG.md
  lua/terrortown/lang/zh_hans.lua
Labels: type/enhancement, priority/low, accepted

#976 Fall Damage: Add ConVars to allow customization for server admins
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/playersettings.lua
Labels: priority/low, accepted, type/feature

#980 Role Changes: Fix double TTT2UpdateTeam hook call on role change
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: priority/low, accepted, severity/moderate

#981 Optimize dmgindicator images
  CHANGELOG.md
  materials/vgui/ttt/dmgindicator/themes/default.png
  materials/vgui/ttt/dmgindicator/themes/simple.png
  materials/vgui/ttt/dmgindicator/themes/vanilla.png
Labels: accepted

#982 Language: Add portuguese translation
  CHANGELOG.md
  lua/terrortown/lang/pt_br.lua
Labels: type/enhancement, accepted

#978 CD: Add primitive continuous deployment workflow
  .github/workflows/cd.yml
Labels: accepted, skip/changelog
