Repository TTT-2/TTT2, pull requests merged in 2023-01, with the labels that each got.

#1010 Small Russian localization update
  lua/terrortown/lang/ru.lua
Labels: accepted, skip/changelog

#1016 Russian localization update
  lua/terrortown/lang/ru.lua
Labels: skip/changelog

#1014 Simplified Chinese and Traditional Chinese localization updates
  CHANGELOG.md
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: type/enhancement, accepted
