Repository TTT-2/TTT2, pull requests merged in 2023-11, with the labels that each got.

#1124 docs: Correct some code documentation mistakes
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_target_data.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsearchbar_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenulist_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dtextentry_ttt2.lua
  gamemodes/terrortown/gamemode/server/sv_network_sync.lua
  gamemodes/terrortown/gamemode/server/sv_shopeditor.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  lua/terrortown/menus/gamemode/base_gamemodemenu.lua
  lua/terrortown/menus/gamemode/base_gamemodemenu/base_gamemodesubmenu.lua
  lua/ttt2/extensions/cvars.lua
  lua/ttt2/extensions/draw.lua
  lua/ttt2/extensions/util.lua
  lua/ttt2/libraries/database.lua
  lua/ttt2/libraries/entspawn.lua
  lua/ttt2/libraries/entspawnscript.lua
  lua/ttt2/libraries/playermodels.lua
  lua/ttt2/libraries/vguihandler.lua
Labels: documentation, accepted, skip-changelog

#1126 docs: Fix a few more code docs and replace dead links
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/entities/ttt_flame.lua
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/client/cl_target_data.lua
  gamemodes/terrortown/gamemode/server/sv_armor.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_entity.lua
  gamemodes/terrortown/gamemode/server/sv_karma.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_propspec.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/old_ttt_element.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_speed.lua
  lua/ttt2/extensions/draw.lua
  lua/ttt2/extensions/table.lua
  lua/ttt2/extensions/util.lua
  lua/ttt2/libraries/bind.lua
  lua/ttt2/libraries/door.lua
  lua/ttt2/libraries/drawsc.lua
  lua/ttt2/libraries/fonts.lua
  lua/ttt2/libraries/none.lua
  lua/ttt2/libraries/targetid.lua
  lua/ttt2/libraries/thermalvision.lua
Labels: documentation, accepted, skip-changelog

#1129 reimplemented @wgetJane's dropclip/reserve
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: type/enhancement, accepted

#1035 Sprint: Fix prediction & refactor logic
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/old_ttt_info.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_playerclass.lua
  gamemodes/terrortown/gamemode/shared/sh_speed.lua
  gamemodes/terrortown/gamemode/shared/sh_sprint.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/gameplay/general.lua
Labels: type/enhancement, accepted

#1132 gave the detective hat a name
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
  lua/terrortown/lang/en.lua
Labels: accepted

#1131 Lang: Add turkish translation
  CHANGELOG.md
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: accepted

#1134 Net: Enhance for 256KB tables
  CHANGELOG.md
  lua/ttt2/extensions/net.lua
Labels: type/enhancement, priority/low, severity/minor

#1136 VGUI: Add Database access to panel elements
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
Labels: type/enhancement, priority/low, severity/minor

#1114 Corpse: Added hook for preventing transfer of found credits
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
  lua/ttt2/libraries/bodysearch.lua
Labels: type/enhancement, accepted

#1137 added incompatible jihad bomb to list
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: accepted, skip-changelog

#1087 fix: More undefined var fixes
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsearchbar_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenubutton_ttt2.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/bug, accepted, skip-changelog

#1139 Update tr.lua
  lua/terrortown/lang/tr.lua
Labels: skip-changelog

#1135 Database: Rework library to use net.SendStream
  CHANGELOG.md
  lua/ttt2/libraries/database.lua
Labels: type/enhancement, priority/low, severity/cosmetic

#1144 Update Simplified Chinese
  lua/terrortown/lang/zh_hans.lua
Labels: accepted, skip-changelog

#1145 Fix nil values for "dcombobox", "playermodels", "dcombobox_ttt2
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dtextentry_ttt2.lua
  lua/terrortown/menus/gamemode/administration/playermodels.lua
Labels: type/bug, accepted
