Repository TTT-2/TTT2, pull requests merged in 2023-10, with the labels that each got.

#1057 allow reading files from data_static
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_traitor_button/init.lua
  lua/ttt2/libraries/entspawnscript.lua
Labels: type/enhancement, accepted

#1072 FIxed a typo I found long ago
  lua/terrortown/menus/gamemode/base_gamemodemenu.lua
Labels: skip-changelog

#1075 fix: Combobox ConVar change callback deletion
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
Labels: accepted

#1076 ci: Update ci versions and remove cd-definition
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: accepted, skip-changelog

#1082 [VIP] added EntranceJew
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
Labels: skip-changelog

#1085 docs: Fix partial docstrings
  gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dpanel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenubutton_ttt2.lua
  gamemodes/terrortown/gamemode/server/sv_networking.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/sh_decal.lua
  gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
Labels: documentation, skip-changelog

#1086 fix: Make sure accessors use DTVars
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
Labels: type/bug, accepted, skip-changelog

#1080 Language: German translations
  CHANGELOG.md
  lua/terrortown/lang/chef.lua
  lua/terrortown/lang/de.lua
Labels: accepted

#1090 fix: Correct network var names
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
Labels: type/bug, accepted, skip-changelog

#1084 entity bringdown
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_flame.lua
  gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
Labels: accepted

#1099 fix: Remove usage of `DTVar()`
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
Labels: accepted, skip-changelog

#1108 use global vectors, especially inside those loops
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_pistol.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_revolver.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_sledge.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_door.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  lua/ttt2/libraries/plyspawn.lua
Labels: accepted

#1109 [Language] Cleanup
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: skip-changelog

#1112 fix dynamic armor leftover damage calculation
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_armor.lua
Labels: accepted

#1113 [Internal] Updated Release Procedure
  RELEASE_PROCESS.md
Labels: accepted, skip-changelog

#1006 T-Buttons: small efficiency boost
  gamemodes/terrortown/entities/entities/ttt_game_text.lua
Labels: accepted, skip-changelog

#1121 [Feature] voice and volume menu
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/gameplay/general.lua
  lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
Labels: accepted, skip-changelog

#1120 [Lang] Cleaned up Language with Param Translation
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: accepted, skip-changelog

#1105 Added: Pulsating healthbar
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/hud_element_base/cl_init.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua
  gamemodes/terrortown/gamemode/shared/huds/base_huds/scalable_hud/cl_init.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/appearance/hudswitcher.lua
  lua/terrortown/menus/gamemode/appearance/miscellaneous.lua
  lua/ttt2/extensions/util.lua
Labels: type/enhancement, accepted

#1123 fix: Deprecate `AccessorFuncDT` instead of removing it
  CHANGELOG.md
  lua/ttt2/libraries/none.lua
Labels: type/bug, accepted
