Repository TTT-2/TTT2, pull requests merged in 2023-12, with the labels that each got.

#984 Shopeditor: Replace syncing with database module
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_shopeditor.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_shopeditor.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
  lua/ttt2/libraries/database.lua
  lua/ttt2/libraries/items.lua
Labels: type/enhancement, priority/low, accepted, waiting

#1148 VGUI: Fix slider textbox
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
Labels: type/bug, accepted, skip-changelog

#1155 Disguiser: Updated Icon
  CHANGELOG.md
  materials/vgui/ttt/hudhelp/item_disguiser.vtf
  materials/vgui/ttt/perks/hud_disguiser.png
Labels: accepted

#1156 Upstream update
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: accepted

#1159 Sprint: Fix stamina start value
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/bug, skip-changelog

#1165 fix: Uppercase letters in filenames are not allowed on workshop upload
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/pure_skin_element.lua
  lua/autorun/server/ttt2_force_download.lua
  materials/vgui/ttt/ammo/box_alyxgun.vmt
  materials/vgui/ttt/ammo/box_alyxgun.vtf
  materials/vgui/ttt/ammo/box_buckshot.vmt
  materials/vgui/ttt/ammo/box_buckshot.vtf
  materials/vgui/ttt/ammo/box_pistol.vmt
  materials/vgui/ttt/ammo/box_pistol.vtf
  materials/vgui/ttt/ammo/box_smg1.vmt
  materials/vgui/ttt/ammo/box_smg1.vtf
  materials/vgui/ttt/ammo/bullet_alyxgun.vmt
  materials/vgui/ttt/ammo/bullet_alyxgun.vtf
  materials/vgui/ttt/ammo/bullet_buckshot.vmt
  materials/vgui/ttt/ammo/bullet_buckshot.vtf
  materials/vgui/ttt/ammo/bullet_pistol.vmt
  materials/vgui/ttt/ammo/bullet_pistol.vtf
  materials/vgui/ttt/ammo/bullet_smg1.vmt
  materials/vgui/ttt/ammo/bullet_smg1.vtf
Labels: accepted, skip-changelog

#1166 ci: Bump neodoc version to fix workflow error
  .github/workflows/ci.yml
Labels: accepted, skip-changelog

#1173 revert most of the change from #1006
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_game_text.lua
Labels: accepted

#1172 Fix missing fastutf8
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted, skip-changelog

#1178 Fix dete call HUD
  CHANGELOG.md
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug, accepted

#1179 Draw: Fix wrong width parameter for split long word
  lua/ttt2/extensions/draw.lua
Labels: skip-changelog

#1182 Bodysearch: Always store all information no matter the trace info
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
Labels: type/bug

#1183 release: prepare v0.12.1b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted

#1200 Fixed water level icon name
  CHANGELOG.md
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug, accepted

#1194 Lua-Server: Fix hidden bugs
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_flame.lua
  gamemodes/terrortown/entities/entities/ttt_traitor_button/shared.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_door.lua
  lua/ttt2/libraries/hudelements.lua
  lua/ttt2/libraries/huds.lua
  lua/ttt2/libraries/items.lua
  lua/ttt2/libraries/orm.lua
Labels: type/bug, accepted

#1214 Issue template: Update Feature request template to use headings
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip-changelog

#1212 Radio: Only owner can pickup
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: accepted

#1201 Beacon: Rework
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: type/enhancement, accepted

#1225 RADAR: Clear when removed, fixes #1070
  CHANGELOG.md
  lua/terrortown/entities/items/item_ttt_radar/shared.lua
Labels: accepted

#1228 make the c4 actually suggest the right button (_really_ fixes #1161)
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: accepted

#1210 hooks for amending spawn positions, because all the data was localed
  CHANGELOG.md
  lua/ttt2/libraries/map.lua
Labels: type/enhancement, accepted

#1222 VGUI: Fix comboboxes by converting strings and numbers
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
Labels: type/bug, accepted

#1231 ttt_game_text mode 4 correction (fixes #972)
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_game_text.lua
Labels: type/bug, accepted

#1223 Database: Fix wrong type in Callbacks
  CHANGELOG.md
  lua/ttt2/libraries/database.lua
Labels: type/bug, accepted

#1236 Fixed Misnamed Language Identitifer
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: type/bug, accepted, skip-changelog

#1232 fix invalid dmginfo being invalid (mitigates #1230)
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug, accepted

#1217 edit equipment accent stock equipment (fixes #964)
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_confgrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_glock.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_m16.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_smokegrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_mac10.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_molotov.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_pistol.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_revolver.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_rifle.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_shotgun.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_sledge.lua
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenubutton_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenulist_ttt2.lua
  lua/autorun/server/ttt2_force_download.lua
  lua/terrortown/entities/items/item_ttt_armor.lua
  lua/terrortown/entities/items/item_ttt_disguiser.lua
  lua/terrortown/entities/items/item_ttt_nodrowningdmg.lua
  lua/terrortown/entities/items/item_ttt_noenergydmg.lua
  lua/terrortown/entities/items/item_ttt_noexplosiondmg.lua
  lua/terrortown/entities/items/item_ttt_nofalldmg.lua
  lua/terrortown/entities/items/item_ttt_nofiredmg.lua
  lua/terrortown/entities/items/item_ttt_nohazarddmg.lua
  lua/terrortown/entities/items/item_ttt_nopropdmg.lua
  lua/terrortown/entities/items/item_ttt_radar/shared.lua
  lua/terrortown/entities/items/item_ttt_speedrun.lua
  lua/terrortown/entities/roles/detective/shared.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/equipment.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
  lua/terrortown/menus/gamemode/roles.lua
  lua/terrortown/menus/gamemode/roles/base_roles.lua
  lua/terrortown/menus/gamemode/shops.lua
  lua/ttt2/libraries/roles.lua
  materials/vgui/ttt/vskin/markers/builtin.vmt
  materials/vgui/ttt/vskin/markers/builtin.vtf
Labels: type/enhancement, accepted

#1238 Release/v0.12.2b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted

#1242 Mark the old Death Note addons as imcompatible
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: keepalive, skip-changelog

#1224 Debug: Add quotation marks to strings in print statements
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/extensions/debug.lua
Labels: type/feature

#1243 Changelog: Move entry to correct position
  CHANGELOG.md
Labels: documentation

#1237 AFK/Idle timer now reads inputs
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
Labels: type/enhancement, keepalive

#1233 Beacon: Added hooks for player detection & death notifying
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
Labels: type/enhancement, keepalive

#1239 describe damage scaling (fixes #1059)
  CHANGELOG.md
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/enhancement, documentation, keepalive

#1261 Global callback fix
  CHANGELOG.md
  lua/ttt2/libraries/database.lua
Labels: type/bug, keepalive

#1263 Keyhelp: Check if voicechat is enabled
  CHANGELOG.md
  lua/ttt2/libraries/keyhelp.lua
Labels: type/bug, keepalive

#1258 Keyhelp: Fixed nil-table indexing
  lua/ttt2/libraries/keyhelp.lua
Labels: keepalive, skip-changelog

#1256 ammo capitalization
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/pure_skin_element.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua
Labels: type/enhancement, keepalive

#1259 targetid show role of named corpses
  CHANGELOG.md
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, keepalive

#1254 fixes #1240: the binoculars can now function
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
Labels: type/bug, keepalive

#1219 make tooltips wider (fixes #1011)
  CHANGELOG.md
  lua/terrortown/menus/score/info.lua
Labels: type/bug, keepalive

#1269 Corpses: Fix looking at disconnected player's corpses
  CHANGELOG.md
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, keepalive

#1264 sv_voiceenable: Added OnChange callback
  gamemodes/terrortown/gamemode/server/sv_voice.lua
Labels: keepalive, skip-changelog

#1268 HUD-help Elements: Use global scale factor
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  lua/ttt2/extensions/draw.lua
  lua/ttt2/libraries/keyhelp.lua
Labels: type/enhancement, keepalive
