Repository TTT-2/TTT2, pull requests merged in 2023-08, with the labels that each got.

#1047 cvar ttt2_bots_lock_on_death fixes #1043
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: type/enhancement, accepted

#1029 Armor: Hotfix for dynamic armor check being inverted
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_armor.lua
Labels: type/bug, accepted

#1054 [Release]: v0.11.7b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: accepted
