Repository TTT-2/TTT2, pull requests merged in 2024-01, with the labels that each got.

#1274 Fixed TTT2FinishedLoading hook not called on server on hot reload
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
Labels: type/bug, keepalive

#1277 Indent Subsettings
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dpanel_ttt2.lua
  lua/terrortown/menus/gamemode/administration/entspawn.lua
  lua/terrortown/menus/gamemode/administration/karma.lua
  lua/terrortown/menus/gamemode/administration/mapentities.lua
  lua/terrortown/menus/gamemode/administration/playersettings.lua
  lua/terrortown/menus/gamemode/administration/roles.lua
  lua/terrortown/menus/gamemode/administration/roundsetup.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/enhancement, keepalive

#1279 Debug: Enable nil entries in nearly sequential table
  CHANGELOG.md
  lua/ttt2/extensions/debug.lua
Labels: type/enhancement

#1278 Shopeditor: Fix missing default values for nil entries
  CHANGELOG.md
  lua/ttt2/libraries/database.lua
Labels: type/bug

#1198 Entity Bringdown volume 2
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/info_manipulate.lua
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_credit_adjust.lua
  gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  gamemodes/terrortown/entities/entities/ttt_damageowner.lua
  gamemodes/terrortown/entities/entities/ttt_knife_proj.lua
  gamemodes/terrortown/entities/entities/ttt_map_settings.lua
  gamemodes/terrortown/entities/entities/ttt_physhammer.lua
  gamemodes/terrortown/entities/entities/ttt_spectator_spawn.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/ttt2/libraries/targetid.lua
Labels: keepalive

#1280 [Release] v0.12.3b
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: keepalive

#1285 Shop: Backend rework part 1/X
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/client/cl_shop.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/rework

#1283 Bindings: Enable in Roundendscreen
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_scoring.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dframe_ttt2.lua
  lua/ttt2/libraries/bind.lua
  lua/ttt2/libraries/vguihandler.lua
Labels: type/enhancement

#1255 binocular search decay
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  lua/terrortown/lang/en.lua
Labels: type/enhancement, keepalive

#1287 Added Delay to Weapon Select
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
Labels: type/bug, keepalive

#1289 Fixed Last Seen Entity
  CHANGELOG.md
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug, keepalive

#1281 docs: Updated readme
  README.md
Labels: documentation, keepalive, skip-changelog

#1288 Improved Weapon Caching
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/gamemode/client/cl_hudpickup.lua
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/ttt2/libraries/entspawnscript.lua
Labels: type/bug, type/enhancement, keepalive

#1290 Shop: Backend rework part 2/X
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_reroll.lua
  gamemodes/terrortown/gamemode/client/cl_shop.lua
  gamemodes/terrortown/gamemode/client/cl_transfer.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_shop.lua
  lua/ttt2/extensions/util.lua
Labels: type/rework

#1241 Rework: Sprinting, Crosshair, FOV/ViewBobbing
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_m16.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_rifle.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_speed.lua
  gamemodes/terrortown/gamemode/shared/sh_sprint.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/administration/sprint.lua
  lua/terrortown/menus/gamemode/appearance/crosshair.lua
  lua/terrortown/menus/gamemode/gameplay/accessibility.lua
  lua/terrortown/menus/gamemode/gameplay/avoidroles.lua
  lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
  lua/ttt2/extensions/player.lua
  lua/ttt2/libraries/entspawnscript.lua
  lua/ttt2/libraries/events.lua
Labels: type/enhancement, keepalive

#1275 Crosshair Fixes and Additions
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/appearance/crosshair.lua
  lua/terrortown/menus/gamemode/gameplay/general.lua
Labels: type/bug, type/enhancement, keepalive

#1297 grenade rework 1/365
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_confgrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_smokegrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_molotov.lua
  materials/vgui/ttt/icon_confgrenade.vmt
  materials/vgui/ttt/icon_confgrenade.vtf
  materials/vgui/ttt/icon_firegrenade.vmt
  materials/vgui/ttt/icon_firegrenade.vtf
  materials/vgui/ttt/icon_smokegrenade.vmt
  materials/vgui/ttt/icon_smokegrenade.vtf
Labels: type/enhancement, keepalive

#1298 Grenades: Fix wrongly using idle animation reset workaround
  gamemodes/terrortown/entities/weapons/weapon_ttt_confgrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_smokegrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_molotov.lua
Labels: type/bug, keepalive, skip-changelog

#1304 F1 menu: Fixed typo in lang files for L.label_crosshair_scale_enable
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: skip-changelog

#1282 Hats: Separate Logic from Player and Hat Model
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
  gamemodes/terrortown/ttt2.fgd
  lua/ttt2/libraries/playermodels.lua
Labels: type/enhancement, keepalive

#1296 Roleselection: Remove Role avoidance, Use plymeta:CanSelectRole
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  lua/terrortown/entities/roles/detective/shared.lua
  lua/terrortown/entities/roles/traitor/shared.lua
  lua/terrortown/entities/roles/ttt_role_base/shared.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/gameplay/avoidroles.lua
  lua/ttt2/libraries/roles.lua
Labels: keepalive

#1247 Updated Simplified Chinese string translation
  CHANGELOG.md
  lua/terrortown/lang/zh_hans.lua
Labels: keepalive

#1162 UI: Add missing equipment/weapon tooltips
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_c4.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_defuser.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: type/enhancement, keepalive

#1308 HUD: Safeguard against max_length not being defined in HUDHelp struct
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/bug, keepalive, skip-changelog

#1305 Make crosshair dot centered
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/bug, skip-changelog

#1203 MarkerVision: A Bomb Radar Rework
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_marker_vision_data.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/autorun/server/ttt2_force_download.lua
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/ttt2/extensions/util.lua
  lua/ttt2/libraries/marker_vision.lua
  materials/vgui/ttt/marker_vision/beacon.vmt
  materials/vgui/ttt/marker_vision/beacon.vtf
  materials/vgui/ttt/marker_vision/c4.vmt
  materials/vgui/ttt/marker_vision/c4.vtf
  materials/vgui/ttt/marker_vision/radio.vmt
  materials/vgui/ttt/marker_vision/radio.vtf
Labels: keepalive, type/rework

#1313 Updated Turkish Localization For New Marker System
  lua/terrortown/lang/tr.lua
Labels: keepalive, skip-changelog

#1316 Icons: Fix missing icons
  lua/autorun/server/ttt2_force_download.lua
Labels: keepalive, skip-changelog

#1311 SWEP: Add SWEP.InvisibleViewModel
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_defuser.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/enhancement, keepalive

#1317 Grenade: Fix grenade decals
  gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua
  gamemodes/terrortown/entities/entities/ttt_smokegrenade_proj.lua
Labels: keepalive, skip-changelog

#1312 made beacon model and icon unique from decoy
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  lua/autorun/server/ttt2_force_download.lua
  materials/vgui/ttt/icon_beacon.vmt
  materials/vgui/ttt/icon_beacon.vtf
  materials/vgui/ttt/icon_decoy.vmt
  materials/vgui/ttt/icon_decoy.vtf
Labels: type/enhancement, keepalive

#1310 Equipment: All builtin items can configured via AllowDrop now
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
  gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
  lua/autorun/server/ttt2_force_download.lua
  materials/vgui/ttt/icon_unarmed.vmt
  materials/vgui/ttt/icon_unarmed.vtf
Labels: type/enhancement, keepalive

#1322 HUD: Scaling for player names when spectating
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: type/enhancement, keepalive

#1328 Database: Fix boolean conversion
  CHANGELOG.md
  lua/ttt2/libraries/database.lua
Labels: type/bug

#1326 prevent dropping weapons that ordinarily are not droppable on death
  gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
Labels: type/bug, keepalive, skip-changelog

#1331 do not leak SendFullStateUpdate events happen
  gamemodes/terrortown/gamemode/client/cl_main.lua
Labels: type/bug, keepalive, skip-changelog

#1333 Fix issues with marks library
  CHANGELOG.md
  lua/ttt2/libraries/marks.lua
Labels: type/bug, keepalive

#1320 UI: Grenade Fuse Timer
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
  lua/terrortown/lang/en.lua
Labels: type/enhancement, keepalive
