Repository TTT-2/TTT2, pull requests merged in 2024-04, with the labels that each got.

#1503 Add locational voice chat range cut-off setting
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_voice.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/chat.lua
Labels: type/enhancement

#1504 Add convar to prevent players without credits from being able to see credits on a body
  CHANGELOG.md
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/roles.lua
  lua/ttt2/libraries/bodysearch.lua
Labels: type/enhancement

#1506 Add multiple voice chat activation modes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
  lua/ttt2/extensions/util.lua
Labels: type/enhancement

#1508 Bugfix: Fixed weapon FOV issues
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
Labels: type/bug

#1500 Revert player iterator
  gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_traitor_check.lua
  gamemodes/terrortown/entities/entities/ttt_weapon_check.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/client/cl_transfer.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  gamemodes/terrortown/gamemode/server/sv_admin.lua
  gamemodes/terrortown/gamemode/server/sv_armor.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
  gamemodes/terrortown/gamemode/server/sv_karma.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_networking.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  gamemodes/terrortown/gamemode/server/sv_shopeditor.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_rolelayering.lua
  lua/terrortown/entities/items/item_ttt_radar/init.lua
  lua/terrortown/events/finish.lua
  lua/terrortown/events/selected.lua
  lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
  lua/ttt2/extensions/util.lua
  lua/ttt2/libraries/credits.lua
  lua/ttt2/libraries/entspawn.lua
  lua/ttt2/libraries/entspawnscript.lua
  lua/ttt2/libraries/plyspawn.lua
  lua/ttt2/libraries/roles.lua
Labels: type/bug, skip-changelog
