Repository TTT-2/TTT2, pull requests merged in 2024-05, with the labels that each got.

#1499 EquipmentEditor: Set clip on buy
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/shared/sh_shopeditor.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/enhancement

#1511 UI: Added Combo Cards
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombocard_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dshopcard_ttt2.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/terrortown/menus/gamemode/shops/base_shops.lua
Labels: type/enhancement

#1509 UI: Adding new panel and extra buttons
  CHANGELOG.md
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_checkmark.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_checkmark.vtf
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_cross.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_cross.vtf
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_lock_closed.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_lock_closed.vtf
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_lock_open.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_lock_open.vtf
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_run.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/icon_run.vtf
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
Labels: type/enhancement

#1513 HUD: Fixed OHI Desync
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/bug

#1473 Voice: Reworked HUD
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttvoice/pure_skin_voice.lua
  gamemodes/terrortown/gamemode/shared/huds/pure_skin/cl_voice.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
Labels: type/enhancement

#1512 F1 menu: Added Option to Change Maps via the F1 Menu
  CHANGELOG.md
  gamemodes/terrortown/content/maps/thumb/test_hardware.png
  gamemodes/terrortown/content/maps/thumb/test_speakers.png
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/helpscreen/commands.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/helpscreen/commands.vtf
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/commands.lua
  lua/terrortown/menus/gamemode/commands/maps.lua
  lua/terrortown/menus/gamemode/equipment.lua
  lua/terrortown/menus/gamemode/roles.lua
  lua/terrortown/menus/gamemode/server_addons.lua
  lua/terrortown/menus/gamemode/shops.lua
  lua/ttt2/extensions/util.lua
  lua/ttt2/libraries/map.lua
Labels: type/enhancement, status/waiting

#1518 Addonchecker: Added Graffiti
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: skip-changelog

#1516 UI/Bindings: Added Run Button to Bindings Menu
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  lua/terrortown/menus/gamemode/bindings/bindings.lua
Labels: type/enhancement

#1519 AddonChecker: Added Mirror Fate
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: skip-changelog

#1520 LANG: "magnet help" no longer needed
  lua/terrortown/lang/en.lua
Labels: skip-changelog

#1521 UI: Admin Commands
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/commands/commands.lua
  lua/terrortown/menus/gamemode/commands/maps.lua
  lua/ttt2/libraries/admin.lua
Labels: type/enhancement

#1526 Fix: Combobox Validity Check
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
Labels: type/bug, skip-changelog

#1525 UI: Unified Spec Color
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttteamindicator/pure_skin_teamindicator.lua
Labels: type/enhancement

#1524 Loadingscreen: Added Screen on Round Restart
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_msgstack.lua
  gamemodes/terrortown/gamemode/client/cl_tips.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/appearance/general.lua
  lua/terrortown/menus/gamemode/appearance/interface.lua
  lua/ttt2/libraries/loadingscreen.lua
  lua/ttt2/libraries/tips.lua
Labels: type/enhancement

#1528 UI: Removed Two Mstack Messages at Round Begin
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_main.lua
  lua/terrortown/lang/en.lua
Labels: type/enhancement, status/waiting

#1530 Marks: Clean up library and improve peformance
  CHANGELOG.md
  lua/ttt2/libraries/marks.lua
Labels: type/bug

#1535 Weaponbase: Fixed weapon dryfire sound interrupting gunshot sounds
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/enhancement

#1532 Gameloop: Complete Restructure
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
  gamemodes/terrortown/entities/entities/ttt_logic_role.lua
  gamemodes/terrortown/entities/entities/ttt_smokegrenade_proj.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_radio.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  gamemodes/terrortown/gamemode/server/sv_admin.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_ent_replace.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
  gamemodes/terrortown/gamemode/server/sv_karma.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_networking.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  gamemodes/terrortown/gamemode/server/sv_voice.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/old_ttt_element.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/old_ttt_info.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttroundinfo/pure_skin_roundinfo.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttteamindicator/pure_skin_teamindicator.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/terrortown/events/base_event.lua
  lua/terrortown/events/bodyfound.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/commands/commands.lua
  lua/ttt2/libraries/admin.lua
  lua/ttt2/libraries/credits.lua
  lua/ttt2/libraries/gameloop.lua
  lua/ttt2/libraries/loadingscreen.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, type/enhancement

#1538 Loadingscreen: Enhancements
  gamemodes/terrortown/content/sound/ttt/loadingscreen.wav
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  lua/terrortown/lang/en.lua
  lua/ttt2/libraries/gameloop.lua
  lua/ttt2/libraries/loadingscreen.lua
Labels: type/enhancement, skip-changelog

#1536 Voice Chat: Added module for battery drain and bar to UI
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttvoice/pure_skin_voice.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  lua/ttt2/libraries/voicebattery.lua
Labels: type/enhancement
