Repository TTT-2/TTT2, pull requests merged in 2024-09, with the labels that each got.

#1602 PlayerReady: Extended Syncing
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/enhancement

#1604 Buttons: Further Fixes
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_entity.lua
  lua/ttt2/libraries/buttons.lua
Labels: type/bug, skip-changelog

#1605 Buttons: Changed Trace Mask
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, skip-changelog

#1606 Buttons: Added Cancelable Hook
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: type/enhancement

#1611 Loadingscreen: Added Serverside Settings
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/roundsetup.lua
  lua/terrortown/menus/gamemode/appearance/general.lua
  lua/ttt2/libraries/loadingscreen.lua
Labels: type/enhancement, skip-changelog

#1609 Sprint Speed: F1 Menu Label Fix
  CHANGELOG.md
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: type/bug

#1610 Buttons: Post Button Init Hook
  CHANGELOG.md
  lua/ttt2/libraries/buttons.lua
Labels: type/enhancement

#1614 TargetID: Fixed and Improved Vehicle Integration
  CHANGELOG.md
  gamemodes/terrortown/content/materials/vgui/ttt/hudhelp/leave_vehicle.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/hudhelp/leave_vehicle.vtf
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  lua/terrortown/lang/en.lua
  lua/ttt2/libraries/keyhelp.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, type/enhancement

#1608 Buttons: Added Serverside Fallback
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/server/sv_entity.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, skip-changelog

#1613 Plyspawn: Find Spawn on Ground
  CHANGELOG.md
  lua/ttt2/libraries/plyspawn.lua
Labels: type/bug

#1618 OverHeadIcon: Add Safeguard Check
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: type/bug, skip-changelog

#1619 F1 Menu: Fixed Haste Mode Setting
  lua/ttt2/libraries/gameloop.lua
Labels: type/bug, skip-changelog

#1621 Shopeditor: Item Buyability Broken due to Cache State
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_changes.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
Labels: type/bug

#1641 Lua ent use fix
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
  gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
  gamemodes/terrortown/gamemode/server/sv_entity.lua
Labels: type/bug

#1642 Loadingscreen: Render Hook Change
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
Labels: type/bug

#1647 refactor(targetid): Use `Vehicle:GetDriver` instead of NWEntity
  CHANGELOG.md
  lua/ttt2/libraries/targetid.lua
Labels: type/enhancement

#1643 Loadingscreen: Fixed Disabling
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  lua/ttt2/libraries/loadingscreen.lua
  lua/ttt2/libraries/tips.lua
Labels: type/bug, type/enhancement

#1650 Fix a huge misstranslation in role config
  lua/terrortown/lang/fr.lua
Labels: skip-changelog
