Repository TTT-2/TTT2, pull requests merged in 2024-08, with the labels that each got.

#1568 Voice: fix panel colors and voice chat not working after round start
  gamemodes/terrortown/gamemode/client/cl_voice.lua
Labels: skip-changelog

#1573 Updated Turkish Localization
  lua/terrortown/lang/tr.lua
Labels: type/enhancement, skip-changelog

#1561 Role Distribution: Add options for "derandomization" for perceptually fairer distributions
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  gamemodes/terrortown/gamemode/shared/sh_role_module.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/roles.lua
  lua/ttt2/extensions/math.lua
Labels: type/enhancement

#1574 Various small fixes found through static analysis
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua
  gamemodes/terrortown/entities/entities/ttt_knife_proj.lua
  gamemodes/terrortown/gamemode/client/cl_radio.lua
  gamemodes/terrortown/gamemode/client/cl_reroll.lua
  gamemodes/terrortown/gamemode/client/cl_transfer.lua
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
  lua/terrortown/entities/items/item_ttt_disguiser.lua
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
  lua/terrortown/menus/gamemode/gameplay/general.lua
  lua/ttt2/extensions/table.lua
  lua/ttt2/libraries/entity_outputs.lua
  lua/ttt2/libraries/gameloop.lua
  lua/ttt2/libraries/weaponrenderer.lua
Labels: type/bug, type/docs

#1487 playermodels: Unique Playermodels at round start
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/playermodels.lua
Labels: type/enhancement

#1578 Lang: Fixes and Improvements
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  lua/terrortown/entities/items/item_ttt_disguiser.lua
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug, skip-changelog

#1577 Corpse: Improvements and Fixes
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_corpse.lua
  gamemodes/terrortown/gamemode/shared/sh_entity.lua
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug

#1579 Added New Derandomization Lines
  lua/terrortown/lang/tr.lua
Labels: type/enhancement, skip-changelog

#1549 vFire: Improved Integration
  CHANGELOG.md
  lua/ttt2/libraries/game_effects.lua
Labels: type/bug, type/enhancement

#1581 Markervision: Fix Unknown Teams
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_marker_vision_element.lua
Labels: type/bug

#1582 Bindings: Fixed Undefined Bindings Breaking Gamemode
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  lua/terrortown/lang/en.lua
  lua/ttt2/extensions/input.lua
Labels: type/bug

#1580 Button Fixes and TargetID Integration
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/shared/sh_entity.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/terrortown/lang/en.lua
  lua/ttt2/libraries/buttons.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, type/enhancement

#1584 Equipment Editor: Fix Inverted
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
Labels: type/bug

#1586 Localization: updated Russian localization file
  lua/terrortown/lang/ru.lua
Labels: skip-changelog

#1587 Updated Turkish Lines
  lua/terrortown/lang/tr.lua
Labels: skip-changelog

#1588 Remove extra spaces and date swaps.
  lua/terrortown/lang/en.lua
Labels: skip-changelog

#1585 UI: Added force role admin command
  CHANGELOG.md
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/commands/commands.lua
  lua/ttt2/libraries/admin.lua
Labels: type/enhancement

#1590 Localization: updated Russian localization file
  lua/terrortown/lang/ru.lua
Labels: skip-changelog

#1592 MapVote: Readded compatibility with old mapvote addons
  lua/ttt2/libraries/gameloop.lua
Labels: type/bug, skip-changelog

#1593 Updated Turkish Lines (Force Player Role)
  lua/terrortown/lang/tr.lua
Labels: skip-changelog

#1451 Credits/Shop: Add hooks for credit related events.
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/shared/sh_shop.lua
  lua/ttt2/libraries/bodysearch.lua
  lua/ttt2/libraries/credits.lua
Labels: type/enhancement

#1597 Player/Roles: Added Fallback Colors
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/bug, skip-changelog

#1599 Sidebar: Added translation to OldTTT
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/hud_elements/tttsidebar/old_ttt_sidebar.lua
Labels: type/bug

#1598 Derandomization: Enabled by Default
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_roleselection.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: skip-changelog

#1595 Fetch: Removed fetching avatar icons from Steam
  CHANGELOG.md
  lua/autorun/client/b-draw_lib.lua
Labels: type/bug, type/enhancement

#1601 Loadingscreen: Cleanup
  lua/ttt2/libraries/gameloop.lua
  lua/ttt2/libraries/loadingscreen.lua
Labels: type/bug, type/enhancement, skip-changelog
