Repository TTT-2/TTT2, pull requests merged in 2024-02, with the labels that each got.

#1338 Over Head Icon improvements
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/enhancement, keepalive

#1340 Fix Weapon Help Width
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/bug, keepalive

#1341 DrawArc: Added Stencil Reset
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/extensions/render.lua
  lua/ttt2/extensions/surface.lua
Labels: type/bug, keepalive

#1343 ci: Add language parser CI that runs on push to master
  .github/workflows/lang-parser.yml
Labels: keepalive, skip-changelog

#1342 fixed view model not rendering
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_c4.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_defuser.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
Labels: type/bug, keepalive, skip-changelog

#1253 Magnetostick: Per role ragdoll pinning permissions (fixes #1100)
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  lua/terrortown/entities/roles/traitor/shared.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/roles/base_roles.lua
  lua/ttt2/libraries/roles.lua
Labels: type/enhancement, keepalive

#1319 UI: Grenade Throw Arc
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/appearance/crosshair.lua
Labels: type/enhancement, keepalive

#1355 DNA Scanner Now Uses Meters
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
Labels: type/enhancement, keepalive

#1353 Radar in Meters
  CHANGELOG.md
  lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
Labels: type/enhancement, keepalive

#1318 Moved Fire and Radius Damage to Game Effects Library
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua
  gamemodes/terrortown/entities/entities/ttt_flame.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/libraries/game_effects.lua
Labels: type/enhancement, keepalive

#1363 Fixed Crosshair for Scales smaller than 1
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/bug, keepalive, skip-changelog

#1315 Shop: Backend rework 3/X
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_shop.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_shop.lua
  gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_shop.lua
Labels: keepalive, type/rework

#1365 Menu: Remove unused misc menu
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/appearance/miscellaneous.lua
Labels: skip-changelog

#1330 Reworked Entities to Use Generic Placeable Base
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
  gamemodes/terrortown/entities/entities/ttt_basegrenade_proj.lua
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_c4.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: type/enhancement, keepalive

#1325 Added Custom World and View Model Rendering
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_c4.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_defuser.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_m16.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_sipistol.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_rifle.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_shotgun.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/extensions/table.lua
  lua/ttt2/libraries/weaponrenderer.lua
Labels: type/enhancement, keepalive

#1336 MarkerVision: Added Static Role/Team Support and API Rework
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_marker_vision_data.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  gamemodes/terrortown/gamemode/shared/sh_marker_vision_element.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/ttt2/libraries/marker_vision.lua
  lua/ttt2/libraries/none.lua
Labels: keepalive

#1367 Debug: Reduce severity of lang identifier warning
  gamemodes/terrortown/gamemode/client/cl_lang.lua
Labels: skip-changelog

#1368 Changelog: Move wrongly placed entries
  CHANGELOG.md
Labels: skip-changelog

#1369 Grenades: Removed BaseClass init
  gamemodes/terrortown/entities/entities/ttt_basegrenade_proj.lua
Labels: type/bug, keepalive, skip-changelog

#1260 scoreboard: show confirmation sources like minihud
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
  lua/terrortown/lang/en.lua
Labels: type/enhancement, keepalive

#1364 TargetID: Disable seeing own spectator nametag
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
Labels: type/enhancement, keepalive

#1373 Entities: Replaced self.BaseClass with BaseClass
  gamemodes/terrortown/entities/entities/base_ammo_ttt.lua
  gamemodes/terrortown/entities/entities/item_ammo_revolver_ttt.lua
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/entities/entities/ttt_smokegrenade_proj.lua
Labels: type/enhancement, keepalive, skip-changelog

#1327 Added World and View Models
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_c4.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
Labels: type/enhancement, keepalive

#1375 Pickup: Added sounds
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
Labels: type/enhancement, keepalive

#1314 UI: 3D Weapon Preview
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dimagecheckbox_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dprofilepanel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dweaponpreview_ttt2.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/ttt2/libraries/weaponrenderer.lua
Labels: type/enhancement, keepalive

#1377 Bodysearch: Fixed hook using wrong variable
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_search.lua
Labels: type/bug, keepalive

#1393 Playersettings: Fixed unwanted shared rederence
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/bug, keepalive, skip-changelog

#1394 Predicted FOV changes: Made FOV calls shared
  gamemodes/terrortown/gamemode/client/cl_player_ext.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/bug, keepalive, skip-changelog

#1396 Doors: Added rounding to door health
  CHANGELOG.md
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, keepalive

#1401 Downloadlists: Removed resource.AddFile from codebase
  CHANGELOG.md
  lua/autorun/server/ttt2_force_download.lua
Labels: type/enhancement, keepalive

#1378 Fonts: Fix wrong setup
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/shared/huds/old_ttt/cl_init.lua
  gamemodes/terrortown/gamemode/shared/huds/pure_skin/cl_init.lua
  lua/ttt2/libraries/marker_vision.lua
Labels: type/bug, keepalive

#1395 C4 UI: Fixed C4 UI accessing wrong BaseClass
  gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua
Labels: type/bug, keepalive, skip-changelog

#1382 Scoreboard: Fixed Icons sometimes missing
  CHANGELOG.md
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug, keepalive

#1405 EntityBase: Changed Owner to Originator
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
Labels: type/bug, keepalive, skip-changelog

#1407 ci: Remove stalebot
  .github/stale.yml
Labels: skip-changelog

#1409 Addonchecker: Added another addon
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: keepalive, skip-changelog

#1374 Entity Base: Added Pickup Handling
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  lua/terrortown/lang/en.lua
Labels: type/enhancement

#1414 Weapon Base: Auto select last weapon on remove
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_c4.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
Labels: type/enhancement

#1300 Migrations: Base for further implementing migrations
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/ttt2/libraries/migrations.lua
Labels: type/feature

#1416 Shop: Invert internal Team buy check
  gamemodes/terrortown/gamemode/shared/sh_shop.lua
Labels: skip-changelog

#1413 Entity Base: Added throw space check
  gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
  gamemodes/terrortown/gamemode/server/sv_player_ext.lua
  lua/terrortown/lang/en.lua
Labels: type/bug, skip-changelog

#1422 Custom World Models: Fixed rendering for custom world models
  lua/ttt2/libraries/weaponrenderer.lua
Labels: type/bug, skip-changelog

#1410 EquipmentMenu: Added check before function call
  CHANGELOG.md
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/bug

#1421 Equipment: Always remove weapon_ttt_unarmed
  gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/bug, skip-changelog

#1424 Equipment Caching: Rework
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  lua/terrortown/menus/gamemode/equipment.lua
  lua/terrortown/menus/gamemode/shops/base_shops.lua
Labels: type/bug

#1429 VIP: Added mexikoedi to VIP list
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
Labels: skip-changelog

#1442 Weapon Renderer: Fixed rendering for weapons not based on the weapon base
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  lua/ttt2/libraries/weaponrenderer.lua
Labels: type/bug

#1444 Placeable Base: Fixed self in table
  gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
Labels: type/bug, skip-changelog

#1445 Addonchecker: Added spring mine
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: skip-changelog
