Repository TTT-2/TTT2, pull requests merged in 2024-10, with the labels that each got.

#1662 Fix weapon pickup through walls
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
Labels: type/bug

#1667 docs: Fix some doc comments
  gamemodes/terrortown/gamemode/client/cl_shop.lua
  gamemodes/terrortown/gamemode/shared/sh_shop.lua
  lua/ttt2/extensions/draw.lua
  lua/ttt2/libraries/bodysearch.lua
Labels: skip-changelog

#1659 Language: Add Korean translation.
  CHANGELOG.md
  lua/terrortown/lang/ko.lua
Labels: type/enhancement

#1673 HUD: Show name of spectated player in old TTT HUD
  CHANGELOG.md
  gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/old_ttt_info.lua
Labels: type/bug
