Repository TTT-2/TTT2, pull requests merged in 2024-03, with the labels that each got.

#1447 Entity: Rework Player Use Handling
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_weapon_pickup.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
  gamemodes/terrortown/gamemode/server/sv_weapon_pickup.lua
  gamemodes/terrortown/gamemode/server/sv_weaponry.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/rework

#1452 AFK timer / incomplete player join bookkeeping
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Labels: type/enhancement

#1437 Radio: Create new UI for remote useable radio
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_tradio.lua
  lua/terrortown/lang/en.lua
Labels: type/rework

#1459 MarkerVision: Added subtitle option
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_marker_vision_data.lua
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  lua/ttt2/libraries/marker_vision.lua
Labels: type/enhancement

#1460 Sounds: Added multiple UI sounds
  CHANGELOG.md
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/helpscreen/sounds.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/vskin/helpscreen/sounds.vtf
  gamemodes/terrortown/gamemode/client/cl_keys.lua
  gamemodes/terrortown/gamemode/client/cl_msgstack.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dbutton_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcard_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dframe_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dimagecheckbox_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dmenubutton_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenubutton_ttt2.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttmstack/old_ttt_mstack.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttmstack/pure_skin_mstack.lua
  gamemodes/terrortown/gamemode/shared/sh_init.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/gameplay/accessibility.lua
  lua/terrortown/menus/gamemode/gameplay/sounds.lua
  lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
  lua/ttt2/extensions/chat.lua
  lua/ttt2/extensions/sound.lua
Labels: type/enhancement

#1464 Crosshair: Show for nades
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
Labels: type/enhancement

#1462 Crosshair: Improvements
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/menus/gamemode/appearance/crosshair.lua
Labels: type/enhancement

#1461 Bugfix: Fixed issue with +use for traitors
  gamemodes/terrortown/gamemode/client/cl_tbuttons.lua
Labels: skip-changelog

#1466 EquipmentMenu: Fix GetClass error
  CHANGELOG.md
  lua/terrortown/entities/items/item_base/shared.lua
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/bug

#1467 Equipment Settings: Item hide irrelevant settings
  CHANGELOG.md
  lua/terrortown/menus/gamemode/equipment/base_equipment.lua
Labels: type/enhancement

#1469 Crosshair: Use default crosshair renderer for binoculars
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
Labels: type/enhancement

#1468 ViewModels: Fix error texture bug
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/bug

#1476 Preventwin: Also prevent timelimit
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_main.lua
Labels: type/enhancement

#1475 Weapons: Show trace for every bullet
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: type/enhancement

#1471 Crosshair: Prevent rendering GMod crosshair
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua
Labels: type/bug

#1294 Shop: Favorites rework
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/cl_equip.lua
  gamemodes/terrortown/gamemode/client/cl_shop.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_shop.lua
  lua/terrortown/migrations/2024_02_16_23_10_favorites_migration.lua
  lua/ttt2/libraries/migrations.lua
Labels: status/waiting, type/rework

#1480 detective search results not be overwritten
  CHANGELOG.md
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug

#1479 bodysearch: TTT2GiveFoundCredits bugfix & new TTT2CanTakeCredits hook
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
  lua/ttt2/libraries/bodysearch.lua
Labels: type/bug

#1492 Roundendscreen: Don't show karma changes if karma is disabled
  CHANGELOG.md
  lua/terrortown/menus/score/info.lua
Labels: type/bug

#1490 Disable locational voice during the preparing phase by default
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_voice.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/chat.lua
Labels: type/enhancement

#1494 Settings: Cleaned up voice settings
  gamemodes/terrortown/gamemode/client/cl_voice.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/gameplay/sounds.lua
  lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
Labels: type/enhancement, skip-changelog

#1496 Settings: Added docs to server voice settings
  lua/terrortown/lang/en.lua
  lua/terrortown/menus/gamemode/administration/chat.lua
Labels: type/enhancement, skip-changelog
