Repository TTT-2/TTT2, pull requests merged in 2024-06, with the labels that each got.

#1541 Entity: Player Ragdoll Check
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/client/cl_radio.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  gamemodes/terrortown/gamemode/shared/sh_entity.lua
  gamemodes/terrortown/gamemode/shared/sh_include.lua
  lua/ttt2/libraries/none.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, type/enhancement

#1542 Is(Super)Admin: Consolidation
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_traitor_button/init.lua
  gamemodes/terrortown/gamemode/client/cl_tbuttons.lua
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
  gamemodes/terrortown/gamemode/server/sv_admin.lua
  gamemodes/terrortown/gamemode/server/sv_hud_manager.lua
  gamemodes/terrortown/gamemode/server/sv_networking.lua
  gamemodes/terrortown/gamemode/server/sv_shopeditor.lua
  gamemodes/terrortown/gamemode/shared/sh_main.lua
  gamemodes/terrortown/gamemode/shared/sh_rolelayering.lua
  lua/terrortown/menus/gamemode/base_gamemodemenu.lua
  lua/ttt2/extensions/cvars.lua
  lua/ttt2/libraries/admin.lua
  lua/ttt2/libraries/database.lua
  lua/ttt2/libraries/entspawnscript.lua
  lua/ttt2/libraries/map.lua
  lua/ttt2/libraries/targetid.lua
  lua/ttt2/libraries/voicebattery.lua
Labels: type/enhancement

#1543 Localization : Fixed Issues With Some Edgecases
  gamemodes/terrortown/gamemode/client/cl_eventpopup.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/ttteventpopup/pure_skin_eventpopup.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/bug, skip-changelog

#1545 Scoreboard/Specs: Changed Groups for Scoreboard Search
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
Labels: type/bug

#1544 Incendiary: Fixed explosion sometimes missing fire
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_basegrenade_proj.lua
  gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua
  lua/ttt2/libraries/game_effects.lua
Labels: type/bug

#1546 docs(Changelog): Add v0.13.2b and move relevant changes to it
  CHANGELOG.md
Labels: type/docs

#1458 ENTITY: New Use workflow
  CHANGELOG.md
  gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
  gamemodes/terrortown/entities/entities/ttt_beacon.lua
  gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua
  gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  gamemodes/terrortown/entities/entities/ttt_decoy.lua
  gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
  gamemodes/terrortown/entities/entities/ttt_health_station.lua
  gamemodes/terrortown/entities/entities/ttt_radio.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  lua/terrortown/lang/en.lua
Labels: type/enhancement, type/rework

#1548 Gameloop: Switched Back to GAMEMODE Table for RoundState
  lua/ttt2/libraries/gameloop.lua
Labels: type/bug, skip-changelog

#1550 Colors: Further Spec Cleanup
  gamemodes/terrortown/gamemode/client/cl_targetid.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttpickup/old_ttt_pickup.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttpickup/pure_skin_pickup.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttpunchometer/pure_skin_punchometer.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/old_ttt_wswitch.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/pure_skin_wswitch.lua
Labels: type/enhancement, skip-changelog

#1551 Corpse: On Fire Feedback
  CHANGELOG.md
  gamemodes/terrortown/content/materials/vgui/ttt/tid/tid_onfire.vmt
  gamemodes/terrortown/content/materials/vgui/ttt/tid/tid_onfire.vtf
  gamemodes/terrortown/gamemode/client/cl_main.lua
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
  lua/ttt2/libraries/targetid.lua
Labels: type/enhancement

#1552 Update addonchecker
  gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
Labels: skip-changelog

#1555 Fixed the new voicehud's embossing effect overlapping the profile picture
  gamemodes/terrortown/gamemode/shared/hud_elements/tttvoice/pure_skin_voice.lua
Labels: skip-changelog

#1554 Weapons: Shotgun changes
  CHANGELOG.md
  gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  gamemodes/terrortown/entities/weapons/weapon_zm_shotgun.lua
Labels: type/enhancement

#1558 fixed spectator voice duck convar typo
  gamemodes/terrortown/gamemode/client/cl_voice.lua
Labels: type/bug, skip-changelog

#1560 using revival block to prevent deprecation warning
  lua/ttt2/libraries/admin.lua
Labels: skip-changelog

#1559 replaced missing body search sounds
  gamemodes/terrortown/gamemode/server/sv_corpse.lua
Labels: type/bug, skip-changelog
