Repository TTT-2/TTT2, pull requests merged in 2025-01, with the labels that each got.

#1668 Hook: Added hook "TTT2PlayDeathScream" for deathscreams
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: type/feature

#1705 Various small chores
  gamemodes/terrortown/entities/entities/ttt_game_text.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/hud_element_base/cl_init.lua
  gamemodes/terrortown/gamemode/shared/hud_elements/tttsidebar/old_ttt_sidebar.lua
  lua/ttt2/libraries/admin.lua
Labels: skip-changelog

#1709 UI: Hide Propspec bind if disabled
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_propspec.lua
  gamemodes/terrortown/gamemode/shared/sh_cvar_handler.lua
  lua/ttt2/libraries/keyhelp.lua
Labels: type/bug

#1710 Gameloop: Split round and time
  CHANGELOG.md
  gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
  gamemodes/terrortown/gamemode/server/sv_main.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/ko.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
  lua/terrortown/menus/gamemode/administration/roundsetup.lua
  lua/ttt2/libraries/gameloop.lua
  lua/ttt2/libraries/loadingscreen.lua
Labels: type/enhancement

#1718 Turkish: Update L10n
  lua/terrortown/lang/tr.lua
Labels: skip-changelog

#1645 Continous Use: Reimplemented
  CHANGELOG.md
  gamemodes/terrortown/gamemode/server/sv_entity.lua
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: type/bug

#1722 vgui: Reworked inheritance
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dbutton_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dlabel_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/droleimage_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenulist_ttt2.lua
Labels: skip-changelog

#1725 RoleLayering: Fixed layered roles not having working toggle
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/drolelayeringreceiver_ttt2.lua
Labels: skip-changelog

#1732 Fix the ordering of param declarations
  gamemodes/terrortown/gamemode/server/sv_player.lua
Labels: skip-changelog

#1745 Fixed Win-Score Breaking Roundend Screen
  lua/terrortown/events/finish.lua
Labels: skip-changelog

#1742 vGui: Fixed Clientside ConVars & Small Misc Fixes
  gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dbutton_ttt2.lua
  gamemodes/terrortown/gamemode/client/cl_vskin/vgui/drolelayeringreceiver_ttt2.lua
Labels: skip-changelog

#1754 feat(radio): Update radio description to reflect current interaction
  gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
  lua/terrortown/lang/de.lua
  lua/terrortown/lang/en.lua
  lua/terrortown/lang/es.lua
  lua/terrortown/lang/fr.lua
  lua/terrortown/lang/it.lua
  lua/terrortown/lang/ja.lua
  lua/terrortown/lang/ko.lua
  lua/terrortown/lang/pl.lua
  lua/terrortown/lang/pt_br.lua
  lua/terrortown/lang/ru.lua
  lua/terrortown/lang/sv.lua
  lua/terrortown/lang/tr.lua
  lua/terrortown/lang/uk.lua
  lua/terrortown/lang/zh_hans.lua
  lua/terrortown/lang/zh_tw.lua
Labels: skip-changelog
